### ISSUE TITLE
Could not get class storage for Traversable.

### ISSUE THREAD

**Issue by 3lvir4** [vimeo/psalm#10682] opened 2024-02-09 20:18 UTC
I was running psalm on a project after modifying some apis to return intersection types with traversable and got an error of the form:
`Uncaught InvalidArgumentException: Could not get class storage for traversable in blablabla`.

Maybe it is normal, I don't know. I find it strange since it is exactly one of the advertised usecases of this php feature.

I reproduced it here:
https://psalm.dev/r/17aef64aef

Is this a bug or something I missed ?

**Comment by weirdan** [comment] 2024-02-10 03:57
Duplicate of #7520

**Closed by weirdan** 2024-02-10 03:57 UTC
