### ISSUE TITLE
False positive RedundantCondition/TypeDoesNotContainNull on optional chaining with null coalesce

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#7741] opened 2022-02-28 23:01 UTC
It appears that psalm ignores optional chaining when determining the type of a variable. You can see that `$petName` should be of type `null|string` because one of the getters in the chain returns a nullable value. This can be further verified with [3v4l](https://3v4l.org/eDcjB) that shows `$petName` is indeed `null`.

Once this is paired with null coalesce in the following step, we get a false positive for both `RedundantCondition` and `TypeDoesNotContainNull`.

https://psalm.dev/r/7f8c79d20d

**Comment by ndench** [comment] 2022-02-28 23:05
With further debugging, I've found that if you use optional chaining on every call in the chain, psalm can then determine the type correctly.

https://psalm.dev/r/1427ce7723

I still think this is a bug, because optional chaining isn't necessary on every part of the chain.

**Comment by jacekkarczmarczyk** [comment] 2022-04-23 16:06
Duplicate of https://github.com/vimeo/psalm/issues/7099

**Comment by orklah** [comment] 2022-04-24 10:13
Yep

**Closed by orklah** 2022-04-24 10:13 UTC
Labels: bug, nullsafe / null coalesce
