### ISSUE TITLE
LSP: Slow analysis when arguments are missing

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#1847] opened 2019-06-25 20:38 UTC
I couldn't find out exactly what's going on.

`LanguageServer::doAnalysis` reanalyzes the current file when it's edited. This takes around 0.15 seconds for a file like `Psalm\Internal\Codebase\ClassLikes`. When the file contains a method call that is missing an argument the execution time goes up to 0.65 seconds which produces a noticeable lag. It doesn't always happen but this is an example where it does:

```php
$this->checkClassReferences();
```

The method requires `(Methods $methods, Progress $progress)` but doesn't get any. As soon as this line is removed the execution time goes back to 0.15 seconds. It doesn't happen for simple arguments like `string`s. I'm guessing that this causes some cascading analysis of those types or something which causes the slowdown.

I noticed this because the `SignatureHelp` lags immensely while typing out the method arguments.

Any idea why this happens?

**Comment by iluuu1994** [comment] 2019-06-25 20:44
Looks like it has nothing to do with missing arguments. Even when all the arguments are provided does the execution time not go down. It's just that method call in general that makes it super slow.

**Comment by muglug** [comment] 2019-06-25 21:26
I can look later, but there are a few things going on when you edit a file.

Ideally method analysis is cached - [this block](https://github.com/vimeo/psalm/blob/904267638f59c798cfd2d1a75987681b12bd7276/src/Psalm/Internal/Analyzer/ClassAnalyzer.php#L1542-L1561) skips analysis for methods that haven't been changed.

However it's sometimes hard to figure out when things haven't been changed.

The current system (when using the language server) goes like this:

Given an AST (`$ast_old`) and text contents (`$contents_old`) for a file, and a new text contents (`$contents_new`) Psalm will first calculate a line-by-line diff of the two, then pass those diff results into a [PartialParserVisitor](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Visitor/PartialParserVisitor.php).

That visitor will then attempt to parse only the diff text. If the parsing fails (if there's a parse error) a _full parse_ will then be attempted (which is slower). I _think_ a full parse is **actually** unnecessary, and it can probably be skipped.

Either way, we now have two ASTs - `$ast_old` and `$ast_new`. Psalm then does an AST diff which, in turn, produces a list of elements whose outer signature has changed and a list of elements whose inner body has changed (but whose outer signature has stayed the same).

Then Psalm takes that list and starts invalidating analysed methods based on what related method signatures/method bodies have been changed.

Then when the file is analysed, only the invalidated methods are checked.

**Comment by iluuu1994** [comment] 2019-06-25 21:35
Thanks for the rundown. I'm not sure if that's it though. Adding the line from above to any method of the class slows it down to 0.75 as mentioned. But then editing other methods still results in an analysis of 0.75 seconds. It looks like Psalm just has some issues with that line in general.

Maybe I'm wrong and that still causes the entire file to be reanalyzed.

**Comment by muglug** [comment] 2019-06-25 22:01
I'll definitely have a look at this later - any slowdowns that can be reproduced on Psalm's sourcecode are good candidates for improvement.

**Comment by muglug** [comment] 2019-06-29 05:23
I'm going to close this for now - benchmarking at home, the most costly thing seems to be the scanning step (numbers when editing a method inside `Classlikes.php`:

```
loading data for reloading took 0.037761926651001
scanning files took 0.072641134262085
 - getting new AST took 0.045391082763672
 - traversing AST took 0.023563861846924
updating ref cache took 0.028800964355469
populating took 0.00015783309936523
```

I don't think there's too much low-hanging fruit there - adding a `(true)` arg to https://github.com/vimeo/psalm/blob/fc549a431feec75ff6f70c8a7e670293f3ecb464/src/Psalm/Codebase.php#L356 reduces the time by about 0.035, but I'm not sure what the ramifications of that are, if any.

**Closed by muglug** 2019-06-29 05:23 UTC
