### ISSUE TITLE
Psalm reports UnevaluatedCode on declare() in script with return if namespace is used 

### ISSUE THREAD

**Issue by remorhaz** [vimeo/psalm#9116] opened 2023-01-16 16:09 UTC
Seems that Psalm erroneously reports `declare(strict_types=1)` as `UnevaluatedCode` if script contains namespace and returns some value.

https://psalm.dev/r/318cbb2876

**Comment by orklah** [comment] 2023-01-16 17:40
Thanks! That's a duplicate of https://github.com/vimeo/psalm/issues/8892

**Closed by orklah** 2023-01-16 17:40 UTC
