### ISSUE TITLE
Can't define template type as docblock-defined class

### ISSUE THREAD

**Issue by alexandrmazur96** [vimeo/psalm#4436] opened 2020-10-28 14:17 UTC
### Implements:

https://psalm.dev/r/9deaec2978

While this variant is correct:

https://psalm.dev/r/1ccfd3fb40

### Extends:

https://psalm.dev/r/d00a4d12ae

While this variant is correct:

https://psalm.dev/r/0419ae23cc

**Comment by weirdan** [comment] 2020-11-25 03:52
Dupe of #4240

**Closed by weirdan** 2020-11-25 03:52 UTC
Labels: bug
