### ISSUE TITLE
conditional types with literal types do not work as expected

### ISSUE THREAD

**Issue by mstilkerich** [vimeo/psalm#8475] opened 2022-09-09 15:10 UTC
Hello,

  according to [the description of the psalm type system](https://psalm.dev/docs/running_psalm/plugins/plugins_type_system/), psalm is able to represent specific values of scalar types as literal types.

So I was expecting something like this to report an error (invalid return type), but it does not:
https://psalm.dev/r/cdf149a5ef

Is this not supported for conditional types? The example is contrived, I would actually like to use it to determine the types of parameters based on another parameter's string value.

**Comment by AndrolGenhald** [comment] 2022-09-09 17:38
Duplicate of #7698. This should be possible, but it will probably take a lot of work, and it might require some improvements to the template system.

**Closed by AndrolGenhald** 2022-09-09 17:38 UTC
