### ISSUE TITLE
Wrong LessSpecificReturnStatement and MoreSpecificReturnType

### ISSUE THREAD

**Issue by thelmuxkriovar** [vimeo/psalm#2670] opened 2020-01-21 06:37 UTC
In some code I wrote that 2 errors would show up no matter what I did, LessSpecificReturnStatement and MoreSpecificReturnType, so I noticed that psalm doesn't know when a list contains for certain only strings. 
Here's some example code that shows the issue https://psalm.dev/r/657911d214

```
$metadata['tags'] = array_filter($metadata['tags'], fn($tag) => is_string($tag));
```

ensures without any doubt that $metadata['tags'] only contains strings.

What's interesting is that

```
$metadata['tags'] = array_map((fn($tag) => (string) $tag), $metadata['tags']);
```
works. However it's not ideal as it's not filtering anything, just string casting.

Maybe psalm doesn't consider array_filter?

**Comment by SignpostMarv** [comment] 2020-01-21 09:29
I believe it's tripping up because `$metadata['tags']` doesn't exist, so is probably defaulting to mixed in it's absence.

see https://psalm.dev/r/1f8c1c193c

**Comment by thelmuxkriovar** [comment] 2020-01-21 09:57
Sorry! The fact that it's missing is only an issue with my test code, the actual code loads a bunch of things from a yaml file, amongst which is 'tags', I even have a check to create an empty array it if it's missing

**Comment by SignpostMarv** [comment] 2020-01-21 10:06
does it make a difference in your local code if you `$metadata['tags'] = array_filter($metadata['tags'], 'is_string');` ?

**Comment by thelmuxkriovar** [comment] 2020-01-21 10:23
Surprisingly it does! I expected it to make no difference, but it absolutely does

**Comment by muglug** [comment] 2020-01-21 13:13
Did you try on latest master?

**Comment by muglug** [comment] 2020-01-21 15:08
Pretty sure this is a dupe of https://github.com/vimeo/psalm/issues/2627 – I'll release soon.

**Closed by muglug** 2020-01-21 15:08 UTC
