### ISSUE TITLE
MissingPropertyType on third party code (ignoreFiles directory)

### ISSUE THREAD

**Issue by leocavalcante** [vimeo/psalm#2388] opened 2019-11-28 19:18 UTC
##### lib/third-party.php
```php
class ThirdPartyCode
{
    public $foo;
}
```

##### src/index.php
```php
require_once 'lib/third-party.php';

$bar = new ThirdPartyCode();

/** @var int $baz */
$baz = $bar->foo;
```

```
ERROR: MissingPropertyType - src\index.php:8:8 - Property ThirdPartyCode::$foo does not have a declared type
$baz = $bar->foo
```

```xml
<?xml version="1.0"?>
<psalm
    totallyTyped="true"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
            <directory name="lib" />
        </ignoreFiles>
    </projectFiles>

    <issueHandlers>
        <LessSpecificReturnType errorLevel="info" />
    </issueHandlers>
</psalm>
```

PS: I'm actually getting this on a third party code inside vendor (regular composer package) this is a code sample that reproduces the issue.

PS 2: Again, sorry if this is me doing bad annotations. Does Psalm have a chat (or something) for such trivial questions like that or it is ok to open issues?

**Comment by weirdan** [comment] 2019-11-28 21:55
Looks like a bug to me. Apparently caused by the fact that the error is reported as originating in `src/index.php` - thus not filtered out.

**Comment by muglug** [comment] 2019-12-01 15:49
> Looks like a bug to me. Apparently caused by the fact that the error is reported as originating in src/index.php - thus not filtered out.

Not quite - third-party-code or otherwise, [Psalm warns when there’s no property type](https://github.com/vimeo/psalm/blob/4052e6dfac18e6dbb052401b9e5dcc477e4d6215/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/PropertyFetchAnalyzer.php#L760). I think your best bet is to stub the third-party code, adding property types.

**Comment by ShiraNai7** [comment] 2020-03-06 12:34
@muglug It looks like a bug to me as well. I'm using `totallyTyped="false"`, `hideExternalErrors="true"` and ignoring the whole `vendor` directory, yet I'm getting errors about missing types on some symfony validator constraint props. I'd expect to just get `mixed` 😕

**Comment by muglug** [comment] 2020-03-06 12:57
Yeah, you're right, I was wrong, this is now fixed.

**Closed** 2020-03-06 12:57 UTC
