### ISSUE TITLE
HTTP request failed in DOMDocument::schemaValidate()

### ISSUE THREAD

**Issue by JamesDeGreese** [vimeo/psalm#6282] opened 2021-08-11 06:28 UTC
Getting error in my gitlab pipeline, ~ two month ago all be good
```
$ vendor/bin/psalm --config=psalm.xml
Uncaught RuntimeException: PHP Error: DOMDocument::schemaValidate(http://www.w3.org/2001/03/xml.xsd): failed to open stream: HTTP request failed! in /foo/bar/vendor/vimeo/psalm/src/Psalm/Config.php:707 in /foo/bar/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
```
my psalm config
```
<?xml version="1.0"?>
<psalm
    errorLevel="4"
    findUnusedVariablesAndParams="true"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
</psalm>
```
How to fix this issue? Can i disable xsd schema validation or something else?

**Comment by orklah** [comment] 2021-08-11 07:10
Closing as duplicate of #6282. The issue was fixed and is pending release

**Closed by orklah** 2021-08-11 07:10 UTC
