### ISSUE TITLE
Resolve enum names in array_column

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#7462] opened 2022-01-22 19:44 UTC
https://psalm.dev/r/f86c37396d

**Comment by orklah** [comment] 2022-01-22 19:48
test https://psalm.dev/r/f86c37396d

**Comment by orklah** [comment] 2022-01-22 19:49
@weirdan there's something wrong with the bot. It picks up a parse error but psalm.dev don't have one

**Comment by orklah** [comment] 2022-01-22 19:52
@vudaltsov It's handled here:
https://github.com/vimeo/psalm/blob/b924032850df54dd05ffae409a709820fd6e688e/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php#L32

It's a plugin dedicated to array_column. The change should not be hard, it must be missing support for Enums

**Comment by vudaltsov** [comment] 2022-01-22 20:18
@orklah , is this relevant? Or should I create a separate issue?
https://psalm.dev/r/7235ae9f81

**Comment by orklah** [comment] 2022-01-22 20:24
Please create a new issue. This is a PHP weirdness. Basically, you can't declare properties on an interface. Psalm will prevent you from doing that and will forbid you to call properties on interfaces.

So YOU can't. But PHP can! They created an internal property on the UnitEnum interface. Psalm will have to handle this

**Comment by weirdan** [comment] 2022-01-23 22:24
> there's something wrong with the bot. It picks up a parse error but psalm.dev don't have one

I think it's caused by different defaults for psalm.dev API and psalm.dev frontend (see https://psalm.dev/r/f86c37396d/results)

**Comment by weirdan** [comment] 2022-01-23 22:32
Should be fixed in psalm/psalm.dev#70

**Comment by orklah** [comment] 2022-12-28 21:30
seems fixed

**Closed by orklah** 2022-12-28 21:30 UTC
Labels: bug, easy problems, type providers, Help wanted
