### ISSUE TITLE
Psalm thinks result of unpacking array is list (8.1)

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#7802] opened 2022-03-20 12:21 UTC
https://3v4l.org/PVohB

https://psalm.dev/r/c1adcfda48

$x is 
```
array(2) {
  ["a"]=>
  int(1)
  ["b"]=>
  int(2)
}
```

not `array{1, 2}`

**Comment by AndrolGenhald** [comment] 2022-03-21 10:34
Duplicate of #7297.

**Closed by AndrolGenhald** 2022-03-21 10:34 UTC
Labels: bug
