### ISSUE TITLE
Psalm crash on `@return (`

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#6159] opened 2021-07-23 09:42 UTC
https://psalm.dev/r/b566eeeb37

**Comment by Jack97** [comment] 2021-07-24 19:58
I've been looking into this issue. The cause is when an `EncapsulationTree` has an empty array of children during the `TypeParser::getTypeFromTree` phase.

Psalm will crash with any variation of the following input for `@return`: `(`, `()`, `((()))` etc. This can be easily fixed by verifying that the parse tree has children before recursively evaluating the type of its first child.

On a slightly unrelated note, I've also found that `(((((string` and `((((string))))` are valid aliases for `string` according to the parser. This doesn't feel quite right to me. The former can be fixed by verifying that the `EncapsulationTree` has been terminated before continuing. However, I'm not sure what to do about the latter 🤔

**Comment by weirdan** [comment] 2021-07-24 20:25
I don't think anything needs to be done about the latter, as long as parens are balanced. Parentheses are valid in a type, they are used to override union vs intersection precedence (e.g. `(A|B) & C`) and to enclose conditional types. So a single type wrapped into a parenthesis is valid as well.

**Comment by Jack97** [comment] 2021-07-24 20:41
Ah okay, thank you for the information - I thought I might have been missing something. I'll raise a PR for this as soon as I can 😄

**Closed** 2021-07-25 10:08 UTC
Labels: bug, causes crash, parser
