### ISSUE TITLE
warn about PHP type juggling array keys

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#5896] opened 2021-06-06 05:50 UTC
while the following passes type analysis, it results in TypeError in runtime.

https://psalm.dev/r/1eca0208ef

ref: https://twitter.com/azjezz/status/1401413622476283906

**Comment by azjezz** [comment] 2021-06-06 05:50
TypeError at runtime: https://3v4l.org/a8am0

**Comment by azjezz** [comment] 2021-06-06 06:11
another example 🤦 https://3v4l.org/fekWt

**Comment by orklah** [comment] 2021-06-06 06:46
This is a duplicate of https://github.com/vimeo/psalm/issues/5426 which have been labeled as "hard problem" I remember we discussed it in other places too, this behaviour by PHP is really hard to predict and handle fully

**Closed by orklah** 2021-06-06 06:46 UTC
