### ISSUE TITLE
Invalid MoreSpecificImplementedParamType error using version 4.3.1

### ISSUE THREAD

**Issue by salvatore-pollaci** [vimeo/psalm#4841] opened 2020-12-14 15:01 UTC
Running the following snippet https://psalm.dev/r/53a08d580c with psalm version 4.3.1 the following error is thrown:
```
ERROR: MoreSpecificImplementedParamType - CommandServiceTest.php - Argument 1 of MyCommandService::execute has the more specific type 'MyCommand', expecting 'mixed' as defined by Service::execute (see https://psalm.dev/140)
    public function execute($request): void
```

whereas with the playground(using commit 2021c81), no such error exists.

Is this a bug in version 4.3.1?

Thanks

**Comment by weirdan** [comment] 2020-12-14 15:17
It is, duplicate of #4767 (fixed in fb88145780a4c57ed0bd99af8a644fb0daf76788).

**Closed** 2020-12-14 15:18 UTC
