### ISSUE TITLE
Argument 2 passed to Psalm\Type::getInt() must be of the type int or null, float given

### ISSUE THREAD

**Issue by mrsuh** [vimeo/psalm#5586] opened 2021-04-06 14:43 UTC
**Lib version** Psalm 4.7.0@d4377c0baf3ffbf0b1ec6998e8d1be2a40971005
**PHP version** 7.4.13
**How to reproduce** You can reproduce error with this repo https://github.com/mrsuh/psalm-error. Just follow README instructions.

**Test file**
```php
<?php

echo 2 ** 80;
```

**Real usage link** https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Calculation/Engineering/ConvertUOM.php#L232

I think it's about int overflow.

**Full error message**
`
Uncaught TypeError: Argument 2 passed to Psalm\Type::getInt() must be of the type int or null, float given, called in /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php on line 323 and defined in /psalm-error/vendor/vimeo/psalm/src/Psalm/Type.php:164
Stack trace:
#0 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php(323): Psalm\Type::getInt(false, 1.2089258196146E+24)
#1 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php(184): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\NonDivArithmeticOpAnalyzer::analyzeNonDivOperands(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), Object(Psalm\Config), Object(Psalm\Context), Object(PhpParser\Node\Scalar\LNumber), Object(PhpParser\Node\Scalar\LNumber), Object(PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Type\Atomic\TLiteralInt), Object(Psalm\Type\Atomic\TLiteralInt), Array, Array, false, false, false, NULL)
#2 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonComparisonOpAnalyzer.php(59): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\NonDivArithmeticOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Internal\Provider\NodeDataProvider), Object(PhpParser\Node\Scalar\LNumber), Object(PhpParser\Node\Scalar\LNumber), Object(PhpParser\Node\Expr\BinaryOp\Pow), NULL, Object(Psalm\Context))
#3 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php(353): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\NonComparisonOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context))
#4 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(228): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context), 0, false)
#5 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(40): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context), false, NULL, false)
#6 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/EchoAnalyzer.php(35): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context))
#7 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(518): Psalm\Internal\Analyzer\Statements\EchoAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Echo_), Object(Psalm\Context))
#8 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Echo_), Object(Psalm\Context), NULL)
#9 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(189): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#10 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#11 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(580): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '...')
#12 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#13 /psalm-error/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#14 /psalm-error/vendor/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check('...', true)
#15 /psalm-error/vendor/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#16 /psalm-error/vendor/vimeo/psalm/psalm(2): require_once('...')
#17 {main}
(Psalm 4.7.0@d4377c0baf3ffbf0b1ec6998e8d1be2a40971005 crashed due to an uncaught Throwable)
`

**Comment by mrsuh** [comment] 2021-04-06 14:46
Hi, psalm-github-bot. I can't

**Comment by orklah** [comment] 2021-04-06 16:07
This has been [fixed ](https://github.com/vimeo/psalm/commit/adc5368b97ba0ae1be46d2b78061318be002e6ae)since but not released yet, that's why you can't reproduce

Duplicate of https://github.com/vimeo/psalm/issues/5505

**Comment by weirdan** [comment] 2021-04-06 17:49
Closing as per @orklah's comment.

**Closed by weirdan** 2021-04-06 17:50 UTC
