### ISSUE TITLE
No way to specify that the shape of an array must be exactly the same

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8397] opened 2022-08-11 11:04 UTC
See https://psalm.dev/r/1ce76391ab
#8395 is related, I thought explicitly specifying that a shape is `sealed-` would've helped, but it didn't: what even is the point of sealing a shape then?

**Comment by AndrolGenhald** [comment] 2022-08-11 14:13
> I thought explicitly specifying that a shape is sealed- would've helped, but it didn't: what even is the point of sealing a shape then?

I don't think the type comparison properly checks it, since it's currently not possible to annotate a `sealed-` type anyway.

Duplicate of #5299.

**Closed by AndrolGenhald** 2022-08-11 14:13 UTC

**Comment by danog** [comment] 2022-08-11 16:39
I meant in my PR, which does support annotating sealed shapes
