### ISSUE TITLE
Bug with traits configuration

### ISSUE THREAD

**Issue by koninka** [vimeo/psalm#2503] opened 2019-12-23 08:22 UTC
Hello, I have the following code:
**EntityRepositoryTrait**
```
trait EntityRepositoryTrait
{
    /**
     * @param ResourceInterface $resource
     *
     * @suppress PhanUndeclaredProperty
     */
    public function traitAdd(ResourceInterface $resource)
    {
        $this->_em->persist($resource);
        $this->_em->flush();
    }

    /**
     * @param ResourceInterface $resource
     *
     * @suppress PhanUndeclaredProperty
     */
    public function traitRemove(ResourceInterface $resource)
    {
        if ($this->find($resource->getId()) !== null) {
            $this->_em->remove($resource);
            $this->_em->flush();
        }
    }

    /**
     * @return string
     */
    public function traitGetAlias()
    {
        return strtolower($this->getClassMetadata()->getReflectionClass()->getShortName());
    }

    /**
     * @return QueryBuilder
     */
    public function traitGetSimpleQB()
    {
        return $this->getSimpleQBWithAlias($this->getAlias());
    }

    /**
     * @param string $alias
     *
     * @return QueryBuilder
     */
    protected function traitGetSimpleQBWithAlias($alias)
    {
        return $this
            ->createQueryBuilder($alias)
            ;
    }
}
```
**And Repo:**
```
class EntityRepository extends BaseEntityRepository implements RepositoryInterface
{
    use EntityRepositoryTrait {
        EntityRepositoryTrait::traitAdd as public add;
        EntityRepositoryTrait::traitGetAlias as public getAlias;
        EntityRepositoryTrait::traitGetSimpleQB as public getSimpleQB;
        EntityRepositoryTrait::traitRemove as public remove;
        EntityRepositoryTrait::traitGetSimpleQBWithAlias as protected getSimpleQBWithAlias;
    }
}
```

When I run `bin/psalm` it fails with exceptions
```
Notice: Undefined index: getalias in /Users/marktertysnyj/sites/7stars-app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Populator.php on line 282
PHP Fatal error:  Uncaught Error: Unsupported operand types in /Users/marktertysnyj/sites/7stars-app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Populator.php:283
Stack trace:
```
and
```
Fatal error: Uncaught Error: Unsupported operand types in /Users/marktertysnyj/sites/7stars-app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Populator.php:283
Stack trace:
```

How to fix this?

**Comment by muglug** [comment] 2019-12-23 08:46
This is a dupe of https://github.com/vimeo/psalm/issues/2490, I think – is it still broken on Psalm master?

**Closed** 2019-12-23 08:46 UTC
