### ISSUE TITLE
psalm-assert for non-empty-list broken since 3.8.2

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#2649] opened 2020-01-17 09:48 UTC
The following code used to work and now errors incorrectly: https://psalm.dev/r/b3ecdd7b42

It seems that the `non-empty-list` assertion incorrectly infers `list<mixed>` instead of `non-empty-list<mixed>`.

```php
<?php
  
/**
 * @psalm-pure
 * @psalm-assert non-empty-list $array
 * @param mixed  $array
 * @throws InvalidArgumentException
 */
function isNonEmptyList($array, string $message = ''): void
{
  // ...
}

/**
 * @psalm-pure
 * @psalm-param mixed $value
 * @psalm-return non-empty-list<mixed>
 */
function consume($value): array
{
    isNonEmptyList($value);
    return $value;
}
```

**Comment by smoench** [comment] 2020-01-17 14:10
duplicate of #2636 which has been resolved in [master](https://github.com/vimeo/psalm/commit/adf230e87348d8b903221c35ea5087e83acefa8b) :-)

**Closed** 2020-01-17 14:31 UTC
