### ISSUE TITLE
Cyclic errors when using with SlevomatCodingStandard

### ISSUE THREAD

**Issue by vladyslavstartsev** [vimeo/psalm#2773] opened 2020-02-08 20:15 UTC
# Bug report
I'm in cyclic warnings between Psalm  and SlevomatCodingStandard.

I'm using Psalm with level max.
For PHP_CodeSniffer (with SlevomatCodingStandard) I use
```xml
<rule ref="SlevomatCodingStandard.PHP.RequireExplicitAssertion"/>
```

### Code snippet that reproduces the problem
original code
https://psalm.dev/r/f961d578ec
this one, is what SlevomatCodingStandard does
https://psalm.dev/r/a68196a7c7
this one what Psalm wants
https://psalm.dev/r/fdb2e71a3b
### Expected output
If we are assigning value to variable and after that doing `assert()` than we surely know which type variable has.

--------------------
Currently I'm just suppressing this, but it will be nice to have.

**Comment by muglug** [comment] 2020-02-08 20:21
Dupe of https://github.com/vimeo/psalm/issues/2442

**Closed by muglug** 2020-02-08 20:21 UTC

**Comment by vladyslavstartsev** [comment] 2020-02-08 20:28
thanks!

**Comment by vladyslavstartsev** [comment] 2020-02-08 20:31
Extra info

Also if you are interested, phpstan (level max + strict) also shows errors.
Output
```bash
  0    Call to function assert() with true will always evaluate to true.                                                             
  0    Instanceof between Kernel and Kernel will always evaluate to true.  

```

**Comment by muglug** [comment] 2020-02-09 04:11
now fixed in master
