### ISSUE TITLE
Incorrect TypeDoesNotContainType - int(0) cannot be identical to positive-int

### ISSUE THREAD

**Issue by xPaw** [vimeo/psalm#3973] opened 2020-08-10 10:42 UTC
I have code like this:
```php
$BatchSize = $somevar ? 20000 : 1000;

foreach( $array1 as $Chunk ) {
	// work
	
	if( --$BatchSize === 0 )
		break;
}

if( $BatchSize > 0 ) {
	foreach( $array2 as $Chunk ) {
		// work

		if( --$BatchSize === 0 ) // TypeDoesNotContainType -int(0) cannot be identical to positive-int
			break;
	}
}
```

Unfortunately I can't repro this on psalm.dev for whatever reason.

**Comment by muglug** [comment] 2020-08-10 14:30
> Unfortunately I can't repro this on psalm.dev for whatever reason.

Please try, else I can't really help debug this

**Comment by xPaw** [comment] 2020-08-10 15:31
Well, I don't know what's up with the site because half the errors that happen locally don't show up on the site.

Because this sample is enough to get it to report locally:
```php
<?php
$BatchSize = random_int(1,2) ? 20000 : 1000;

$array1=[];
$array2=[];

foreach( $array1 as $Chunk ) {
	// work
	
	if( --$BatchSize === 0 )
		break;
}

if( $BatchSize > 0 ) {
	foreach( $array2 as $Chunk ) {
		// work

		if( --$BatchSize === 0 ) // TypeDoesNotContainType -int(0) cannot be identical to positive-int
			break;
	}
}
```

**Comment by muglug** [comment] 2020-08-10 16:29
Mind creating a separate repo that reproduces the issue then?

**Comment by muglug** [comment] 2020-08-10 16:30
Maybe the reason it doesn't show up on the site is that it's fixed in latest master.

**Comment by xPaw** [comment] 2020-08-10 17:20
> Mind creating a separate repo that reproduces the issue then?

Not sure why there is a need for one. Here's psalm.xml (it's just basic one with file specified).

```
<?xml version="1.0"?>
<psalm
	errorLevel="1"
	resolveFromConfigFile="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="https://getpsalm.org/schema/config"
	xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
	<projectFiles>
		<file name="test.php" />
	</projectFiles>
</psalm>
```

**Comment by muglug** [comment] 2020-08-11 11:41
Does this also fail with latest Psalm master though?

**Comment by xPaw** [comment] 2020-08-11 11:46
I don't know because it's not exactly trivial to run psalm master locally.

**Comment by muglug** [comment] 2020-08-11 13:14
OK, then I'm assuming this is fixed in master.

**Closed by muglug** 2020-08-11 13:14 UTC

**Comment by muglug** [comment] 2020-08-11 13:15
BTW you can use `composer require vimeo/psalm:dev-master` or, if you use the Phar, `composer require psalm/phar:dev-master`
