### ISSUE TITLE
Enum values as class strings

### ISSUE THREAD

**Issue by vlakarados** [vimeo/psalm#9938] opened 2023-06-20 13:49 UTC
Basically here's working code sample:
https://psalm.dev/r/c71751d4fe

Also is it possible to create a hint for enum values to be all class-strings?:

**Comment by vlakarados** [comment] 2023-06-21 05:09
Seems to be related
https://github.com/vimeo/psalm/issues/8978

**Comment by orklah** [comment] 2023-06-21 19:37
Seems like the structure that holds the value of a case was designed to only hold literals (ints or strings): https://github.com/vimeo/psalm/blob/958d1ca69592ff7f288113f86169a1eba8565038/src/Psalm/Storage/EnumCaseStorage.php#L12

That's fine in most cases because literals are pretty much the most precise type you could end up with... except for class-string (the literal `Foo` is less precise than `Foo::class` even if they're the same thing in the end.

So yeah, the value property here should be transformed into an Atomic (so it can handle any type from Psalm (as long as we only have one but it should be ok)

that should not be very hard given in most place, we're actually jumping hoops to extract the literal from an Atomic or the other way around

**Comment by weirdan** [comment] 2024-03-09 23:53
Fixed in #10165 (`master`).

**Closed as completed by weirdan** 2024-03-09 23:53 UTC
Labels: bug, Help wanted, enum
