### ISSUE TITLE
Unexpected divider $ak_id

### ISSUE THREAD

**Issue by voku** [vimeo/psalm#2350] opened 2019-11-15 15:12 UTC
Hi, I tried this command ```php7.3 Framework/thirdparty/psalm.phar --alter --issues=MissingReturnType,MissingClosureReturnType,InvalidFalsableReturnType,InvalidReturnType,InvalidNullableReturnType,MissingParamType,MismatchingDocblockParamType,MismatchingDocblockReturnType,UnnecessaryVarAnnotation --config App/scripts/githooks/psalm.xml --php-version=7.0 .``` but it fails for different parts of the application, here is a example:

code:
```
if (isset($KundenArray[$KundenArray[$ak_id]->parent])) {
    $KundenArray[$KundenArray[$ak_id]->parent]->full_child_id_array[] = $ak_id;
}
```

version: (current release)
```
3.6.5@b1aae0d1a5a11908e0e5f9eb6795ab7bb3f43577
```

trace:
```
<phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Type\Reconciler::reconcileKeyedTypes" on line: <145>
	Called with params: Array(2) {'$KundenArray[$KundenArray[$ak_id]->parent]' => Array(1) {0 => Array(1) {0 => "isset" |  } |  } | '$KundenArray' => Array(1) {0 => Array(1) {0 => "=int-or-string-array-access" |  } |  } |  }, Array(6) {'kundeLib::$TraegerCacheArray' => Object(_HumbugBoxb6ab9d012af3\Psalm\Type\Union) | '$this' => Object(_HumbugBoxb6ab9d012af3\Psalm\Type\Union) | '$ak_id' => Object(_HumbugBoxb6ab9d012af3\Psalm\Type\Union) | '$KundenArray' => Object(_HumbugBoxb6ab9d012af3\Psalm\Type\Union) | '$KundenArray[$ak_id]' => Object(_HumbugBoxb6ab9d012af3\Psalm\Type\Union) |  ...  }, Array(0), Array(3) {'$ak_id' => True | '$KundenArray' => True | '$KundenArray[$ak_id]' => True |  }, Object(_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\StatementsAnalyzer), Array(0), False, Object(_HumbugBoxb6ab9d012af3\Psalm\CodeLocation)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyze" on line: <265>
	Called with params: Object(_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxb6ab9d012af3\PhpParser\Node\Stmt\If_), Object(_HumbugBoxb6ab9d012af3\Psalm\Context)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\StatementsAnalyzer->analyze" on line: <310>
	Called with params: Array(2) {0 => Object(_HumbugBoxb6ab9d012af3\PhpParser\Node\Stmt\If_) | 1 => Object(_HumbugBoxb6ab9d012af3\PhpParser\Node\Stmt\If_) |  }, Object(_HumbugBoxb6ab9d012af3\Psalm\Context), Object(_HumbugBoxb6ab9d012af3\Psalm\Context), True

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze" on line: <764>
	Called with params: Object(_HumbugBoxb6ab9d012af3\Psalm\Context), Object(_HumbugBoxb6ab9d012af3\Psalm\Context)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod" on line: <381>
	Called with params: Object(_HumbugBoxb6ab9d012af3\PhpParser\Node\Stmt\ClassMethod), Object(_HumbugBoxb6ab9d012af3\Psalm\Storage\ClassLikeStorage), Object(_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\ClassAnalyzer), Object(_HumbugBoxb6ab9d012af3\Psalm\Context), Object(_HumbugBoxb6ab9d012af3\Psalm\Context)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\ClassAnalyzer->analyze" on line: <161>
	Called with params: Object(_HumbugBoxb6ab9d012af3\Psalm\Context), Object(_HumbugBoxb6ab9d012af3\Psalm\Context)

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\FileAnalyzer->analyze" on line: <264>
	Called with params: Null

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Codebase\Analyzer->_HumbugBoxb6ab9d012af3\Psalm\Internal\Codebase\{closure}" on line: <409>
	Called with params: 7372, "/home/lmoelleken/vdmg/Framework/modules/Framework/Stammdaten/Stammdaten/legacy/kundeLib.php"

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Codebase\Analyzer->doAnalysis" on line: <220>
	Called with params: Object(_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\ProjectAnalyzer), 1

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Codebase\Analyzer->analyzeFiles" on line: <387>
	Called with params: Object(_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\ProjectAnalyzer), 1, True

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/psalter.php>"_HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\ProjectAnalyzer->check" on line: <296>
	Called with params: "/home/lmoelleken/vdmg/"

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/psalm.php>"include" on line: <66>
	Called with params: "phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/psalter.php"

	By: <phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/psalm>"require_once" on line: <5>
	Called with params: "phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/psalm.php"

	By: </home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar>"require" on line: <14>

Start:16:04:10 ErrorNo:1 Error:Unexpected divider $ak_id File:phar:///home/lmoelleken/vdmg/Framework/thirdparty/psalm.phar/src/Psalm/Type/Reconciler.php Line:110

PHP SELF:Framework/thirdparty/psalm.phar
Script Filename:Framework/thirdparty/psalm.phar
Script Name:Framework/thirdparty/psalm.phar
```

**Comment by muglug** [comment] 2019-11-15 15:27
Dupe of #2328 (fixed in master)

**Closed by muglug** 2019-11-15 15:27 UTC
