### ISSUE TITLE
Adding an element to an array inside an ArrayAccess object is borked

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#8391] opened 2022-08-10 09:50 UTC
https://psalm.dev/r/969b295793

**Comment by AndrolGenhald** [comment] 2022-08-10 15:23
Duplicate of #6350. Let me know if you end up debugging it and find out what's going on! It's never been enough of a priority for me to spend a lot of time on :slightly_frowning_face:

**Closed by AndrolGenhald** 2022-08-10 15:23 UTC
