### ISSUE TITLE
Support non-standard vendor dir

### ISSUE THREAD

**Issue by DeepDiver1975** [vimeo/psalm#467] opened 2018-01-24 14:06 UTC
the vendore dir is currently hardcoded - https://github.com/vimeo/psalm/blob/78e34c05484d83b2bfd8c55fa6cefbec10866c96/src/command_functions.php#L31

but this directory is configurable in composer.json and should be respected

**Comment by muglug** [comment] 2018-01-24 14:20
Dupe of https://github.com/vimeo/psalm/issues/252

But I’ll try and get to this tonight

**Comment by DeepDiver1975** [comment] 2018-01-24 14:21
THX

**Closed by muglug** 2018-01-24 14:20 UTC
