### ISSUE TITLE
Unpacking functions causes invalid types and missing information

### ISSUE THREAD

**Issue by pkly** [vimeo/psalm#8285] opened 2022-07-19 10:43 UTC
When you do something like the following, invalid information is retrieved from the unpacked array and psalm will complain that arguments are missing

https://psalm.dev/r/3ec4e021d5

**Comment by AndrolGenhald** [comment] 2022-07-19 14:13
Duplicate of #8276.

**Closed by AndrolGenhald** 2022-07-19 14:13 UTC
