### ISSUE TITLE
TypeDoesNotContainType on embedded constants

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#878] opened 2018-07-10 03:43 UTC
I'm getting these on Psalm 2.0.6@beeab32:

```
ERROR: TypeDoesNotContainType - src/Command/InfectionCommand.php:271:13 - string(phpdbg) does not contain string(cli)
        if (\PHP_SAPI === 'phpdbg') {
```
Sure it does not, but that's how one can detect currently used SAPI.

```
ERROR: TypeDoesNotContainType - src/Finder/Iterator/RealPathFilterIterator.php:28:13 - string(/) does not contain string(\)
        if ('\\' === \DIRECTORY_SEPARATOR) {
```
This is OS detection related code.

Seems bogus, what do you think?

**Comment by muglug** [comment] 2018-07-10 03:46
Dupe of https://github.com/vimeo/psalm/issues/867, fixed in master :) I'll create a release momentarily

**Closed** 2018-07-10 03:47 UTC
