### ISSUE TITLE
Psalm incorrectly reports Inaccessible property inside unset

### ISSUE THREAD

**Issue by kapitancho** [vimeo/psalm#4548] opened 2020-11-14 01:21 UTC
This sample code show the issue:
https://psalm.dev/r/5708e0f636

There is a class marked as psalm-immutable and a unsetting a value in a completely unrelated array should be no problem unset($a[$test->value]);
Instead an 

> ERROR: InaccessibleProperty - test::$value is marked readonly
is reported.

**Comment by muglug** [comment] 2020-11-14 13:55
Dupe of #4529

**Closed by muglug** 2020-11-14 13:55 UTC
