### ISSUE TITLE
Interface violation isn't reported if method is specified in docblock

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#7735] opened 2022-02-25 13:45 UTC
https://psalm.dev/r/a50dc23247

There should be an error on line 10, because the implementation violates interface `Foo` contract.

**Comment by orklah** [comment] 2022-02-25 17:21
Yeah, I'll close as duplicate of https://github.com/vimeo/psalm/issues/5786#issuecomment-846541853, @method and @property are lacking support for a lot of advanced uses

**Closed by orklah** 2022-02-25 17:21 UTC
