### ISSUE TITLE
Weird @psalm-type parse error

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6956] opened 2021-11-22 09:30 UTC
https://psalm.dev/r/c85af598b1
Removing the second parameter fixes it: https://psalm.dev/r/b3f76a70ca

**Comment by orklah** [comment] 2021-11-22 09:39
duplicate of https://github.com/vimeo/psalm/issues/6928. A PR has been started to fix this in https://github.com/vimeo/psalm/issues/6929

**Closed by orklah** 2021-11-22 09:39 UTC
