### ISSUE TITLE
The order of types in type union affects the result in @psalm-type

### ISSUE THREAD

**Issue by ptomulik** [vimeo/psalm#7127] opened 2021-12-11 09:26 UTC
The two examples below are essentially same, but the first fails while the second doesn't

first: https://psalm.dev/r/fe31ac99f5
second: https://psalm.dev/r/2c87a894f0

The difference is:

``@psalm-type Items=list<string>|string`` (fails)
vs
``@psalm-type Items=string|list<string>`` (works)

**Comment by ptomulik** [comment] 2021-12-11 09:30
Simplified examples:
https://psalm.dev/r/a1ea987a33
https://psalm.dev/r/3f38e1c3b0

**Comment by orklah** [comment] 2021-12-11 09:36
This is a duplicate of https://github.com/vimeo/psalm/issues/6928 (the parser just stops reading after the `>`: https://psalm.dev/r/4502bc4e1c)

@spawnia started fixing that in https://github.com/vimeo/psalm/pull/6929 but it's not finished yet

**Closed by orklah** 2021-12-11 09:36 UTC
