### ISSUE TITLE
Enum case initialized from const fails to infer value

### ISSUE THREAD

**Issue by ievgenklymenko** [vimeo/psalm#9797] opened 2023-05-18 12:43 UTC
Hi!

 [Psalm.dev reproduction](https://psalm.dev/r/c091c3e36c)

I have this working enum code:

```
use Symfony\Component\HttpFoundation\Response;

enum ResponseStatusCodeEnum: int
{
    case Ok = Response::HTTP_OK; // const int '200'
}
```

When I run Psalm it crashes RuntimeException with this error before even showing files progress bar:

```
Failed to infer case value for Ok

  at vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:1427
    1423▕                         ),
    1424▕                     );
    1425▕                 }
    1426▕             } else {
  ➜ 1427▕                 throw new RuntimeException('Failed to infer case value for ' . $stmt->name->name);
    1428▕             }
    1429▕         }
    1430▕
    1431▕
```

..from the code above this, there is this $case_type resolution, which fails:

```
$case_type = SimpleTypeInferer::infer(...
```

Ignoring this file in config unfortanatly does not help. Same error evakes.

I hope issue not duplicate !
Thank you!!

**Comment by weirdan** [comment] 2023-08-13 03:44
Duplicate of #8978

**Closed by weirdan** 2023-08-13 03:44 UTC
Labels: bug, causes crash, enum
