### ISSUE TITLE
preg_callback_array closure param

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1896] opened 2019-07-03 19:38 UTC
psalm doesn't appear to like a shaped parameter on the callback for `preg_replace_callback()`, regardless of how the function is defined within psalm- original `array<array-key, mixed>`, or `array<int, string>` in 6f096ffd

this impacts #1884, as the ci won't pass the changes.

**Comment by muglug** [comment] 2019-07-05 14:58
Should be fixed!

**Closed by muglug** 2019-07-05 14:58 UTC

**Comment by SignpostMarv** [comment] 2019-07-05 18:22
> Should be fixed!

nope: https://psalm.dev/r/2e4a1ff83c

```php
<?php
echo preg_replace_callback(
  '/[a-z]/',
  /**
  * @param array{0:string, 1:string} $matches
  */
  function (array $matches) : string {
    return mb_strtoupper($matches[1]);
  },
  'abc'
);
```
> Psalm output (using commit 216d8ae): 
> 
> ERROR: ArgumentTypeCoercion - 7:3 - Argument 2 of preg_replace_callback expects callable(array<int, string>):string, parent type Closure(array{0: string, 1: string}):string provided

**Comment by muglug** [comment] 2019-07-05 18:53
Well that’s _another_ bug

**Comment by SignpostMarv** [comment] 2019-07-05 18:58
> Well that’s _another_ bug

shall I file separately or are you already tracking it down?

**Comment by muglug** [comment] 2019-07-05 19:38
actually not a bug - I've modified the docblock in that PR to fit.

https://psalm.dev/r/dff4e3d60f shows why it's expected behaviour.

**Comment by SignpostMarv** [comment] 2019-07-06 05:29
ah: there's no guarantee from the method signature that the array shape will match, unless one does deep analysis of the regex ?
