### ISSUE TITLE
PHP 8 - Psalm does not infer the type when $object::class is used and matches a conditional tree

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#4583] opened 2020-11-17 08:28 UTC
Types are not inferred when `$object::class` is used and it matches an expression:

- `match()`: https://psalm.dev/r/c8780ac2d1
- `switch`: https://psalm.dev/r/8e495619c1
- `if`: https://psalm.dev/r/2b18331a1e

May be related to #4544

**Comment by orklah** [comment] 2021-11-04 19:52
This is more or less a duplicate of https://github.com/vimeo/psalm/issues/4583 and will be fixed by https://github.com/vimeo/psalm/pull/6823

**Closed** 2021-11-04 19:55 UTC
Labels: bug
