### ISSUE TITLE
Getting error in ignored files

### ISSUE THREAD

**Issue by marvin255** [vimeo/psalm#3904] opened 2020-07-27 22:30 UTC
Hello. 

After update from 3.11.0 to 3.12.2 i'm starting to get errors:
```bash
ERROR: ParseError - vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:15:35 - Syntax error, unexpected T_MATCH on line 15 (see https://psalm.dev/173)
interface ParametersMatch extends Match


ERROR: ParseError - vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:34:40 - Syntax error, unexpected ';', expecting '{' on line 34 (see https://psalm.dev/173)
    public function with(...$arguments);


ERROR: ParseError - vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:47:40 - Syntax error, unexpected ';', expecting '{' on line 47 (see https://psalm.dev/173)
    public function withAnyParameters();
```

My config xml is:
```xml
<?xml version="1.0"?>
<psalm
    totallyTyped="false"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config file:///var/www/vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="./" />
        <ignoreFiles>
            <directory name="vendor" />
            <directory name="Tests" />
            <directory name="Docker" />
            <directory name="Resources" />
        </ignoreFiles>
    </projectFiles>

    <issueHandlers>
        <LessSpecificReturnType errorLevel="info" />

        <!-- level 3 issues - slightly lazy code writing, but provably low false-negatives -->

        <InternalMethod errorLevel="info" />

        <MissingClosureReturnType errorLevel="info" />
        <MissingReturnType errorLevel="info" />
        <MissingPropertyType errorLevel="info" />
        <InvalidDocblock errorLevel="info" />
        <MisplacedRequiredParam errorLevel="info" />

        <PropertyNotSetInConstructor errorLevel="suppress" />
        <MissingConstructor errorLevel="info" />
        <MissingClosureParamType errorLevel="info" />
        <MissingParamType errorLevel="info" />

        <RedundantCondition errorLevel="info" />

        <DocblockTypeContradiction errorLevel="info" />
        <RedundantConditionGivenDocblockType errorLevel="info" />

        <UnresolvableInclude errorLevel="info" />

        <RawObjectIteration errorLevel="info" />
    </issueHandlers>
</psalm>
```

`vendor` folder must be ignored.

Runnig psalm like `./vendor/bin/psalm --no-cache -c psalm.xml` so looks like that this is not a cache issue.

**Comment by marvin255** [comment] 2020-07-27 22:31
> Hey @marvin255, can you reproduce the issue on https://psalm.dev ?

Can't reproduce on psalm.dev. Most like related to phpunit 9.5.

**Comment by weirdan** [comment] 2020-07-27 23:21
Please update to dev-master, where this should be already fixed.

**Comment by weirdan** [comment] 2020-07-27 23:23
Or require `nikic/php-parser:4.6.*`.

**Comment by weirdan** [comment] 2020-07-27 23:23
Duplicate of #3900

**Closed by weirdan** 2020-07-27 23:23 UTC
