### ISSUE TITLE
`new` on objects

### ISSUE THREAD

**Issue by sergkash7** [vimeo/psalm#8355] opened 2022-08-01 13:25 UTC
https://psalm.dev/r/0f7a5134d0

**Comment by weirdan** [comment] 2022-11-19 05:11
`$test` is already an object, so you don't really need `new` in the `throw`; you can just `throw $test`. With this said, using `new` on objects is valid in PHP (https://3v4l.org/E7seZ), so Psalm should learn to understand that.

**Comment by weirdan** [comment] 2022-11-19 05:12
Snippet to match the updated issue title: https://psalm.dev/r/3e0baa6d4d

**Comment by orklah** [comment] 2022-11-19 07:40
For anyone interested in fixing this, the issue is located in UnionTypeComparator::isContainedBy. This method receives two Unions and is in charge of returning whether or not the first is covered by the second. In this case, the first is a union containing a `TAnonymousClassInstance` that extends `Exception` while the second is an Union that looks like `Exception|Throwable` (two TNamedObjects) that was created here: https://github.com/vimeo/psalm/blob/54edbdabf631b707fefab3ac38257d6a8b419e7d/src/Psalm/Internal/Analyzer/Statements/ThrowAnalyzer.php#L57

The method should return that the first is contained by the second (because any object inheriting `Exception` is an Exception) but it doesn't because `TAnonymousClassInstance` used to not track what it inherits from since some months and this was not added since

**Comment by weirdan** [comment] 2022-11-19 19:33
> For anyone interested in fixing this, the issue is located in `UnionTypeComparator::isContainedBy()`

Is it? I would expect it to be fixed in `NewAnalizer` actually (see my snippet above).

> `TAnonymousClassInstance` used to not track what it inherits from since some months and this was not added since

It tracks `extends` now: https://github.com/vimeo/psalm/blob/4e17585093880573d1ba4164bf7ca4370a5903e5/src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php#L227

Or are you saying that even if `NewAnalyzer` correctly inferred that `new $object` returns an object of `get_class($object)` class it won't help because nothing actually uses `TAnonnymousClassInstance::$extends`?

**Comment by orklah** [comment] 2022-11-19 20:12
Sorry, my answer was very partial, I focused on the second error from original post `ERROR: InvalidThrow - 6:1 - Cannot throw object as it does not extend Exception or implement Throwable`

> it won't help because nothing actually uses TAnonnymousClassInstance::$extends

Exactly, extends is not used for much since I've added it for another issue. That's why Psalm emits an InvalidThrow even when the anonymous class is an Exception

I kinda omitted the first issue but yeah, that needs fixing too. However, I find the error in your snippet more justified. I'm not sure we should allow instantiating `object`. Any Named Object of Anonymous class should be fine though (and it's not right now)

**Comment by weirdan** [comment] 2022-11-19 20:49
> That's why Psalm emits an InvalidThrow even when the anonymous class is an Exception

But it doesn't: https://psalm.dev/r/2b4b9580e5

I do believe the only issue here is calling `new` on objects. Once that is solved, everything else should just work.

I suspect `TAnonymousClassInstance::$extends` is not really needed, and we can drop it before the 5.0 release. I'm going to check that next.

**Comment by weirdan** [comment] 2022-11-19 20:52
> I'm not sure we should allow instantiating `object`.

Why not?

**Comment by orklah** [comment] 2022-11-19 20:58
extends is used for Psalter at least. I added it here: https://github.com/vimeo/psalm/pull/5146

> Why not?
Impossible to check for parameters, for visibility of  __construct or purity. At the very least, it should emit a MixedMethodCall like we do for a `new $a;` where $a is mixed

>But it doesn't: https://psalm.dev/r/2b4b9580e5

Indeed. Not sure why https://psalm.dev/r/83779ff61d fails then. Maybe it sees $a(); as a function call and then makes new on a mixed return? That's weird

**Comment by weirdan** [comment] 2022-11-19 21:18
> extends is used for Psalter at least. I added it here: https://github.com/vimeo/psalm/pull/5146

Yeah, that's what I found. Not going to remove it then.

> Not sure why [psalm.dev/r/83779ff61d](https://psalm.dev/r/83779ff61d) fails then.

That's because currently Psalm knows that whatever happens (e.g. `UnknownClass`), the result of `new` would still be an `object`, so `object` is used as a fallback when inference fails.

**Comment by weirdan** [comment] 2022-11-19 21:21
> Impossible to check for parameters, for visibility of `__construct` or purity. 

All good points.

>  At the very least, it should emit a `MixedMethodCall` like we do for a `new $a;` where `$a` is `mixed`.

I think I'll go with this option. `UnknownClass` is clearly misleading.

**Closed** 2022-11-19 21:37 UTC
Labels: enhancement, easy problems, type reconciliation, Help wanted, good first issue
