### ISSUE TITLE
Union of structlike arrays incorrectly upcasted to single structlike array

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1158] opened 2019-01-02 03:00 UTC
This is probably actually a feature request, rather than strictly speaking a bug ;-)

Psalm (incorrectly as it loses useful type information) upcasts the union of structlike arrays to single structlike array. e.g. `array{a:string, b:string}|array{c:string, d:string}` is treated like `array{a?:string, b?:string, c?:string, d?:string}`. While `array{a?:string, b?:string, c?:string, d?:string}` is a parent type, it doesn't contain all the information that the original type did: testing for a key which only occurs in a single branch of the union should imply the other key in that structlike array exists (i.e. if the key `a` is set this should imply `b` also is, and if it is not set then this should imply both `c` and `d` are).

---

https://getpsalm.org/r/5fcf0c1761

```php
<?php

/**
 * @param array{a: string, b: string}|array{c: string, d: string} $struct_AB_or_CD
 */
function foo(array $struct_AB_or_CD): string
{
    if (isset($struct_AB_or_CD['a'])) {
        return $struct_AB_or_CD['b'];
    }

    return $struct_AB_or_CD['c'] . $struct_AB_or_CD['d'];
}
```

Psalm output (using commit 6fbf395): 
```
ERROR: PossiblyUndefinedArrayOffset - 9:16 - Possibly undefined array key $struct_AB_or_CD['b']

ERROR: PossiblyUndefinedArrayOffset - 12:12 - Possibly undefined array key $struct_AB_or_CD['c']

ERROR: PossiblyUndefinedArrayOffset - 12:36 - Possibly undefined array key $struct_AB_or_CD['d']
```

Expected:
```
No issues!
```

**Comment by muglug** [comment] 2019-01-02 09:58
Duplicate of #704. Basically this won't happen - sorry.

**Closed by muglug** 2019-01-02 09:58 UTC

**Comment by aidantwoods** [comment] 2019-01-02 13:33
I wonder whether it would be preferable for Psalm to instead complain upon seeing the union of structlike array annotations like the above (and perhaps suggest the annotation it would have assumed in current behaviour be used instead)?

In my example, this isn't such an issue (the type being contravariant means using a parent type won't break anything—it just necessitates more checks by the function body), however looking at #704 where the annotation is instead used in a place where the type should be covariant, this does indeed open the potential to break things, as @weirdan pointed out (since assuming a parent type isn't type-safe here).

To clarify: I think requiring we use classes to get similar behaviour is reasonable (as opposed to Psalm having to make complicated type deductions), just the silent upcasting v.s. what is written is perhaps not desirable?

**Comment by weirdan** [comment] 2019-01-02 14:02
> just the silent upcasting v.s. what is written is perhaps not desirable?

Yeah, issuing a warning in such cases seems a good way to reduce confusion factor.
