### ISSUE TITLE
bug: incorrect `InvalidReturnStatement`

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#7884] opened 2022-04-21 15:35 UTC
example: https://psalm.dev/r/6e6d6c6ba4

in this case, the return value for `SomeClass::getRepositoryForSpecificEntity` is correct, if `Foo` is given, `FooRepository` ( which is `SpecificEntityRepositoryInterface<Foo>` ) is returned, and same for `Bar`.

However, psalm doesn't seem to like this.

remove the parent interface also doesn't solve the issue: https://psalm.dev/r/9b90dd17aa

the only way to make this code work, is by doing the following: https://psalm.dev/r/0a72564d9d

though, this is not ideal if we want to support 20 entities for example.

**Comment by azjezz** [comment] 2022-04-21 15:36
the issue is not related to `match`, as the same problem is happening with `if`:

https://psalm.dev/r/8ff4779722

**Comment by AndrolGenhald** [comment] 2022-04-21 16:21
Duplicate of #5572, unfortunately Psalm doesn't currently support narrowing template types outside of specific support for conditional types (this is actually slightly more complicated than it seems at first since there can be multiple parameters (and properties for class templates) that use the template).

**Closed by AndrolGenhald** 2022-04-21 16:21 UTC
