### ISSUE TITLE
False positive RedundantConditionGivenDocblockType and DocblockTypeContradiction when using conditional return type and ?? operator

### ISSUE THREAD

**Issue by Etherlord** [vimeo/psalm#4818] opened 2020-12-09 11:54 UTC
https://psalm.dev/r/34a7ba3dbb

**Comment by muglug** [comment] 2020-12-09 14:22
Dupe of the https://github.com/vimeo/psalm/issues/4817 (opened 8 hours ago)

**Closed by muglug** 2020-12-09 14:22 UTC

**Comment by muglug** [comment] 2020-12-10 00:39
This is now fixed in master
