### ISSUE TITLE
Redis setOption() emit InvalidScalarArgument

### ISSUE THREAD

**Issue by shandyDev** [vimeo/psalm#7709] opened 2022-02-21 10:39 UTC
Hi
I found (look subject):
https://psalm.dev/r/a002786368
Because of stub: https://github.com/vimeo/psalm/blob/4.x/stubs/phpredis.phpstub#L390

Why first param it is string?
If look to source code of phpredis https://github.com/phpredis/phpredis/blob/develop/redis_arginfo.h#L652 this is should be integer

**Comment by shandyDev** [comment] 2022-02-21 11:08
Also found https://psalm.dev/r/0244c2dfb5
(misses constants in stubs?)

**Comment by orklah** [comment] 2022-02-21 13:14
@kkmuffme could there be an error in the stub introduced in https://github.com/vimeo/psalm/pull/7614?

**Comment by simitter** [comment] 2022-02-21 16:29
Based on the stubs many methods can now return the class Redis itself which seems wrong?

Example: exists

https://psalm.dev/r/ab6bfb4ce0

**Comment by orklah** [comment] 2022-02-21 17:45
I don't personally use Redis, but this looks to be messy...

Just for reference:
An issue was created here: https://github.com/vimeo/psalm/issues/7581 because psalm's definitions seemed wrong on some methods. Apparently, they were also wrong on the stub provided by Redis repo itself (https://github.com/vimeo/psalm/issues/7581#issuecomment-1032349112). A new stub was created based on an unmerged PR created by a maintainer of the repo here: https://github.com/phpredis/phpredis/pull/2015

But apparently it would be wrong too?

I think this would really benefit from having someone comparing redis documentation with our current stubs and making fixes when necessary. If possible, a check in source code or some reproducable snippet could be used to update both their documentation and Psalm stub if there are still errors

**Comment by kkmuffme** [comment] 2022-02-21 18:57
@orklah the stubs are by the maintainer of phpredis, so they're definitely correct - however the stubs are still a WIP https://github.com/phpredis/phpredis/pull/2015 as you say
Those stubs pass phpredis' own tests (see the PR title), so I assume they're correct.

The problem with phpredis is that
a) the documentation does not match the code
b) the stubs (not psalm's, I mean the one currently provided by phpredis main branch) do not match the documentation AND the actual code
c) their release cycle is forever long and random, so god knows when those WIP stubs will actually be correct and merged.

Currently only b) is addressed in that PR (but apparently not correct in all cases, even though the tests pass), but a) will/should also be addressed there.
So now we're stuck with c)

If we actually want to get correct stubs, we'd need to feed back any feedback to that PR to get it corrected there (and also directly fix it in the psalm stubs), so within (hopefully) a couple months we will have correct stubs.

===

@simitter yes I know it's really weird. e.g.
`public function expire(string $key, int $timeout): Redis|bool;`

No idea, how this returns Redis. Can you fix those and please also feed back your changes to https://github.com/phpredis/phpredis/pull/2015 so we dont get forked stubs and reduce amount of maintenance necessary in the long run

===

@shandyDev yes, constants are missing in the stubs too. Please put them together and comment on https://github.com/phpredis/phpredis/pull/2015 so we get the included there (and thereby also in psalm)

**Comment by AndrolGenhald** [comment] 2022-02-21 19:31
For reference, I added the generated stubs [here](https://github.com/AndrolGenhald/php-extension-stub-generator/blob/master/generated_stubs/redis-5.3.7.phpstub). Unfortunately Reflection doesn't support return types for extensions, so I'm not sure how useful it'll be.

**Comment by orklah** [comment] 2022-02-21 20:14
@simitter see https://github.com/phpredis/phpredis/pull/2015#issuecomment-1047189052. The fact that it returns a Redis instance is expected in some cases, depending on the context of the usage. Stub is correct on that.

However, this is not a standard behaviour, so it might need a special handling if you want to have the exact returned type.

I'm not personally interested in improving the inference on that more than what's described on the stub. If you want, I could guide you in the creation of a plugin for that if you're up for it.

@shandyDev Thanks for your feedback. It will be fixed upstream. Feel free to send a PR to fix this in Psalm!

@AndrolGenhald That's unfortunate. It creates a good skeleton for building on it, but it means starting from scratch on each new php version if we want updated stubs...

**Comment by AndrolGenhald** [comment] 2022-02-21 20:17
> That's unfortunate. It creates a good skeleton for building on it, but it means starting from scratch on each new php version if we want updated stubs...

That's one of several reasons I decided to improve `@since` and only use generated stubs for diffing to see what's changed when I did #7641.

**Comment by simitter** [comment] 2022-02-22 12:06
> The fact that it returns a Redis instance is expected in some cases, depending on the context of the usage. Stub is correct on that.
> 
> However, this is not a standard behaviour, so it might need a special handling if you want to have the exact returned type.
> 
> I'm not personally interested in improving the inference on that more than what's described on the stub. If you want, I could guide you in the creation of a plugin for that if you're up for it.

Thank you for clearing that up. The stubs make sense now.
I'll suppress it in CI for now and may look to create a plugin at a later date.

**Comment by ADmad** [comment] 2022-03-04 04:53
> I'm not personally interested in improving the inference on that more than what's described on the stub. If you want, I could guide you in the creation of a plugin for that if you're up for it.

@orklah I totally understand you not wanting to spend time one this to deal with Redis' wacky API. But in that case adding this stub doesn't bring much value when we have to resort to suppressing the errors caused by the `Redis|` return type. It would have been better of just wait for someone to develop a plugin for it.

**Comment by ADmad** [comment] 2022-03-04 04:58
IMHO this stub should be just reverted.

**Comment by orklah** [comment] 2022-03-04 06:15
I don't agree. If someone is using Redis new mode in order to retrieve a Redis instance, stubs would be completely wrong for them leading to a lot of confusion.

I prefer have imprecise but correct stubs than stubs that are precise but only for a some cases

That aside, the stub fixes a lot of other errors so it won't just be reverted

**Comment by ADmad** [comment] 2022-03-04 06:58
https://www.youtube.com/watch?v=hou0lU8WMgo

The stub is technically correct, the best kind of correct :slightly_smiling_face:

**Comment by kkmuffme** [comment] 2022-03-04 11:57
Updated the stubs to latest version to include the fix for setOption https://github.com/vimeo/psalm/pull/7752

In general the phpredis stubs are amazing now - I could remove 100s of unused psalm-suppress thanks to the new stubs.

**Comment by orklah** [comment] 2022-03-04 19:50
I'll close this, the original issue is now fixed and we use official Redis stubs. If someone is interested in building a Redis plugin (or a type provider in Psalm's core), feel free to create a new issue for discussion

Also, I think constants were not included. Feel free to PR them here or in Redis repo if they accept those

**Closed by orklah** 2022-03-04 19:50 UTC
Labels: bug, internal stubs/callmap, Help wanted
