### ISSUE TITLE
schemaValidate error in Psalm/Config.php:707 

### ISSUE THREAD

**Issue by Ar2r** [vimeo/psalm#6281] opened 2021-08-11 06:20 UTC
I`m using latest vimeo/psalm (4.9.2)

When i run psalm without internet i get error:

`vendor/bin/psalm --config=psalm.xml`

My config:
```xml
<?xml version="1.0"?>
<psalm
    errorLevel="4"
    findUnusedVariablesAndParams="true"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
</psalm>
```

```
Uncaught RuntimeException: PHP Error: DOMDocument::schemaValidate(http://www.w3.org/2001/03/xml.xsd): failed to open stream: HTTP request failed! in /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Config.php:707 in /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(2, 'DOMDocument::sc...', '/builds/Gz-QYUc...', 707, Array)
#1 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Config.php(707): DOMDocument->schemaValidate('/builds/Gz-QYUc...')
#2 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Config.php(652): Psalm\Config::validateXmlConfig('/builds/Gz-QYUc...', '<?xml version="...')
#3 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Config.php(625): Psalm\Config::loadFromXML('/builds/Gz-QYUc...', '<?xml version="...', '/builds/Gz-QYUc...', '/builds/Gz-QYUc...')
#4 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Internal/CliUtils.php(487): Psalm\Config::loadFromXMLFile('/builds/Gz-QYUc...', '/builds/Gz-QYUc...')
#5 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(552): Psalm\Internal\CliUtils::initializeConfig('/builds/Gz-QYUc...', '/builds/Gz-QYUc...', 'console', Object(Composer\Autoload\ClassLoader), false)
#6 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(1007): Psalm\Internal\Cli\Psalm::loadConfig('/builds/Gz-QYUc...', '/builds/Gz-QYUc...', 'console', Object(Composer\Autoload\ClassLoader), false, Array)
#7 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(216): Psalm\Internal\Cli\Psalm::initConfig('/builds/Gz-QYUc...', Array, 'vendor', Object(Composer\Autoload\ClassLoader), '/builds/Gz-QYUc...', 'console', false, Array)
#8 /builds/Gz-QYUcE/1/cde106/self/backend/libs/sms-gate/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#9 {main}
(Psalm 4.9.2@00c062267d6e3229d91a1939992987e2d46f2393 crashed due to an uncaught Throwable)
```

**Comment by Ar2r** [comment] 2021-08-11 06:28
To reproduce you need to install vimeo/psalm (4.9.2)
Then turn off the internet!
Run: `vendor/bin/psalm --config=psalm.xml`

And then you will get the same error:
```
Uncaught RuntimeException: PHP Error: DOMDocument::schemaValidate(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Config.php:707 in /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(2, 'DOMDocument::sc...', '/Users/artur/Ph...', 707, Array)
#1 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Config.php(707): DOMDocument->schemaValidate('/Users/artur/Ph...')
#2 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Config.php(652): Psalm\Config::validateXmlConfig('/Users/artur/Ph...', '<?xml version="...')
#3 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Config.php(625): Psalm\Config::loadFromXML('/Users/artur/Ph...', '<?xml version="...', '/Users/artur/Ph...', '/Users/artur/Ph...')
#4 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Internal/CliUtils.php(487): Psalm\Config::loadFromXMLFile('/Users/artur/Ph...', '/Users/artur/Ph...')
#5 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(552): Psalm\Internal\CliUtils::initializeConfig('/Users/artur/Ph...', '/Users/artur/Ph...', 'console', Object(Composer\Autoload\ClassLoader), false)
#6 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(1007): Psalm\Internal\Cli\Psalm::loadConfig('/Users/artur/Ph...', '/Users/artur/Ph...', 'console', Object(Composer\Autoload\ClassLoader), false, Array)
#7 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(216): Psalm\Internal\Cli\Psalm::initConfig('/Users/artur/Ph...', Array, 'vendor', Object(Composer\Autoload\ClassLoader), '/Users/artur/Ph...', 'console', false, Array)
#8 /Users/artur/PhpstormProjects/RGSB/libs/sms-gate_rgsb/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#9 {main}
(Psalm 4.9.2@00c062267d6e3229d91a1939992987e2d46f2393 crashed due to an uncaught Throwable)
```

**Comment by orklah** [comment] 2021-08-11 07:09
Hi! This was fixed [here](https://github.com/vimeo/psalm/pull/6229) but not yet released

**Comment by weirdan** [comment] 2021-08-11 07:30
Duplicate of #6228

**Closed by weirdan** 2021-08-11 07:30 UTC
