### ISSUE TITLE
@template-implements / extends does not recognize custom type definitions.

### ISSUE THREAD

**Issue by jsiefer** [vimeo/psalm#4696] opened 2020-11-24 22:06 UTC
Hi

I would expected that `@type Values` is an acceptable parameter in `@template-implements Test<Values> `

See https://psalm.dev/r/16c5eaff3b

**Comment by weirdan** [comment] 2020-11-25 03:53
It's `@psalm-type`, not `@type`.
Also it's a duplicate of #4240.

**Closed by weirdan** 2020-11-25 03:53 UTC
