### ISSUE TITLE
Should orphaned psalm tags should be discovered by the -- findUnusedCode option?

### ISSUE THREAD

**Issue by githoober** [vimeo/psalm#3562] opened 2020-06-11 04:10 UTC
https://psalm.dev/r/bf0713b780

I cannot find anything that would allow me to see these orphaned tags. In my project, surprisingly, they were found by PHPStan checks.

**Comment by AndrolGenhald** [comment] 2022-06-26 13:14
Duplicate of #3166.

**Closed by AndrolGenhald** 2022-06-26 13:14 UTC
Labels: enhancement

**Comment by weirdan** [comment] 2023-02-16 02:07
Fixed in #9314
