### ISSUE TITLE
UndefinedThisPropertyFetch within property_exists() check

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#7922] opened 2022-05-03 08:30 UTC
I am loading dynamic objects and testing for some properties via property_exists(). Unfortunately, this causes UndefinedThisPropertyFetch errors.

https://psalm.dev/r/0a435e7d65

I tested the same code with phpstan and it produces no errors.

Seems like this is an old issue: https://github.com/vimeo/psalm/issues/5913

Thank you.

**Comment by AndrolGenhald** [comment] 2022-05-03 14:42
I'll close this as a duplicate of #2206, but I hope for this to be possible eventually by intersecting classes with object-with-properties (eg `A&object{foo: mixed}`) so that `property_exists` and `isset` can add properties to an existing class.

**Closed by AndrolGenhald** 2022-05-03 14:42 UTC
