### ISSUE TITLE
Cannot infer type of `array_pop`'s result in parameterised classes

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1066] opened 2018-11-06 22:00 UTC
```
/**
 * @template T
 */
class Collection
{
    /** @var array<T> */
    private $items;
  
    /**
     * @param array<T> $items
     */
    public function __construct(array $items)
    {
        $this->items = $items;
    }
  
    /**
     * @return T
     * @throws RuntimeException
     */
    public function get()
    {
        if (!empty($this->items)) {
            return array_pop($this->items);
        }
        throw new RuntimeException();
    }
}
```

Produces

> INFO: MixedReturnStatement - 26:13 - Could not infer a return type

https://getpsalm.org/r/6344ecd25e

**Comment by weirdan** [comment] 2018-11-06 22:12
Simplified: https://getpsalm.org/r/cc709e672e

Somehow `array_pop()` accepting a reference messes things up (and it's sticky, as `fNoRef()` call after `fRef()` also fails to resolve types).

**Comment by muglug** [comment] 2018-11-21 04:09
@vasily-kartashov I think this is only a problem with getpsalm.org, now fixed in https://github.com/psalm/getpsalm.org/commit/4e91eed

**Comment by muglug** [comment] 2018-11-21 13:41
Reopening - looking at the code further, the problem is that anything _but_ `array_pop` and `array_push` have this bad behaviour, as @weirdan's example makes clear. Bug added in https://github.com/vimeo/psalm/commit/957600623cecb344775518c4b98a376010453bc1

**Closed** 2018-11-21 17:38 UTC
Labels: bug, mixed
