### ISSUE TITLE
Asserts working really bad for unions

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#5939] opened 2021-06-16 09:52 UTC
https://psalm.dev/r/b1de1933b5

**Comment by SCIF** [comment] 2021-06-16 09:54
None of them provided expected `null|'a'|'b'` (obviously 4th case is not fully valid, but still weird output, imho).

**Comment by SCIF** [comment] 2021-06-16 10:28
Same for literal: https://psalm.dev/r/82cd00f668

**Comment by SCIF** [comment] 2021-06-17 22:36
@muglug , probably here is your input is required

During investigation I found next line: https://github.com/vimeo/psalm/blob/master/src/Psalm/Storage/Assertion.php#L46
It's clear that unions cannot be handled in this case. Also, documentation [page](https://psalm.dev/docs/annotating_code/assertion_syntax/) has no union mentioned as possible syntax/type.

**Comment by SCIF** [comment] 2021-06-17 22:52
I can see in code multiple occurances of using of code like `$assertion->rule[0][0]`. Why it was done? Intentionally? I changed code a little bit and my tests of union scalar passed fine. So I'm curious if it's easy as transforming those hardcoded `[0][0]` into `foreach`'es or there is much more work and better to prohibit using unions by throwing InvalidDocBlock issues?

**Comment by weirdan** [comment] 2024-01-31 18:09
I believe it's essentially a duplicate of #6831

**Closed by weirdan** 2024-01-31 18:09 UTC
Labels: enhancement, docblock assertions
