### ISSUE TITLE
Results of assertions with unions seems to be too widely accepted

### ISSUE THREAD

**Issue by LeSuisse** [vimeo/psalm#3109] opened 2020-04-09 09:02 UTC
I would have expected to get a `PossiblyInvalidArgument` for the call of `takesZeroOrOne` protected by the assertion in the following example: https://psalm.dev/r/4d8d023ee1

**Comment by weirdan** [comment] 2020-04-09 09:28
Actually it looks like assertion didn't work as intended and narrowed the type too much: https://psalm.dev/r/70eb2762fb

**Comment by ktomk** [comment] 2020-08-02 17:08
Is it intended to have this working with assertions? I've been playing with `@psalm-assert-if-true` and `string` which worked fine.

Then I wanted not only string but an [enum](https://psalm.dev/docs/annotating_code/typing_in_psalm/#specifying-stringint-options-aka-enums) (with strings, similar to here as with integers) and I didn't get an error for the annotation but could see it not working:

`@psalm-assert-if-true A::STATUS_* $param`

Which made me look-up [assertion syntax in the docs](https://psalm.dev/docs/annotating_code/assertion_syntax/) and how I read it, there is no support for enums with assertions, it's just `string` or `int`.

**Comment by AndrolGenhald** [comment] 2022-02-19 00:01
Duplicate of #6831.

**Closed by AndrolGenhald** 2022-02-19 00:01 UTC
Labels: bug
