### ISSUE TITLE
false-positive InvalidArgument for `strip_tags`

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#5330] opened 2021-03-05 14:37 UTC
as of PHP 7.4, `strip_tags` accepts `list<string>` as a second argument.

see: https://3v4l.org/MDih9
see: https://psalm.dev/r/75a1953276

**Comment by weirdan** [comment] 2021-03-08 21:11
Duplicate of #4317

**Closed by weirdan** 2021-03-08 21:11 UTC
