### ISSUE TITLE
Psalm emit LessSpecificImplementedReturnType for overriden in interface IteratorAggregate::getIterator()

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#2093] opened 2019-09-03 08:55 UTC
https://psalm.dev/r/06135065b8

Expected: no issues.
Actual: 
```
Psalm output (using commit da23c2e):

ERROR: LessSpecificImplementedReturnType - 14:33 - The return type 'Iterator<array-key, int>' for IterableInts::getIterator is more specific than the implemented return type for ConstantArrayInts::getiterator 'Iterator'
```

```php
<?php
interface IterableInts extends IteratorAggregate {
    /**
     * @return int[]|Iterator
     */
    public function getIterator(): Iterator;
}
class ConstantArrayInts implements IterableInts
{
    public function getIterator(): Iterator
    {
    	yield from [1, 2, 3, 4];
    }
}
```

**Comment by muglug** [comment] 2019-09-03 22:07
The solution is to add the same docblock: https://psalm.dev/r/7987d959cf

It's not great, but Psalm has trouble deciding which interface docblock to use for `getIterator` — the one from `IterableInts` or the one from `IteratorAggregate` — so it uses neither.

Dupe of #1756

**Closed by muglug** 2019-09-03 22:07 UTC

**Comment by andrew-demb** [comment] 2020-02-14 08:00
Seems liike this ticket fixed with https://github.com/vimeo/psalm/commit/8989737e51811dc21cd92b9e40406bd859a1a82d
