### ISSUE TITLE
false positive on UnusedVariable on a static function use (&$var)

### ISSUE THREAD

**Issue by williamdes** [vimeo/psalm#6108] opened 2021-07-15 22:20 UTC
Psalm thinks `$prevErrorHandler` is not used and `--alter --issues=UnusedVariable` would remove `$prevErrorHandler = ` breaking the code
```php
            $prevErrorHandler = set_error_handler(
                static function (int $level, string $message, string $file, int $line) use (&$prevErrorHandler) {
                    if ($level === E_USER_DEPRECATED) {
                        $templateLine = 0;
                        if (preg_match('/ at line (\d+)[ .]/', $message, $matches)) {
                            $templateLine = (int) $matches[1];
                        }

                        throw new Error($message, $templateLine);
                    }

                    return $prevErrorHandler ? $prevErrorHandler($level, $message, $file, $line) : false;
                }
            );
```
Source: https://github.com/phpmyadmin/phpmyadmin/blob/0fbfa7b0e0c1254ddf4f7d0bb95a1ca29fd2c982/libraries/classes/Command/TwigLintCommand.php

### Baseline
```xml
  <file src="libraries/classes/Command/TwigLintCommand.php">
    <MixedArgument occurrences="6">
      <code>$code</code>
      <code>$file</code>
      <code>$info['exception']</code>
      <code>$info['file']</code>
      <code>$info['file']</code>
      <code>$info['template']</code>
    </MixedArgument>
    <MixedArgumentTypeCoercion occurrences="1"/>
    <MixedArrayAccess occurrences="7">
      <code>$info['exception']</code>
      <code>$info['file']</code>
      <code>$info['file']</code>
      <code>$info['file']</code>
      <code>$info['template']</code>
      <code>$info['valid']</code>
      <code>$info['valid']</code>
    </MixedArrayAccess>
    <MixedAssignment occurrences="3">
      <code>$code</code>
      <code>$file</code>
      <code>$info</code>
    </MixedAssignment>
    <MixedFunctionCall occurrences="1">
      <code>$prevErrorHandler($level, $message, $file, $line)</code>
    </MixedFunctionCall>
    <UnusedVariable occurrences="2">
      <code>$prevErrorHandler</code>
      <code>$prevErrorHandler</code>
    </UnusedVariable>
  </file>
 ```

**Comment by williamdes** [comment] 2021-07-15 22:20
> Hey @williamdes, can you reproduce the issue on https://psalm.dev ?

https://psalm.dev/r/a3e3c08c94

**Comment by orklah** [comment] 2021-07-15 22:24
I think this is a duplicate of #4536

**Comment by simPod** [comment] 2021-07-16 08:42
@orklah I've just stumbled upon #4536 again and therefore this issue as well. Sometimes it is not possible to use non-functional approach which is suggested as a workaround in #4536. IMO #4536 should be kept open.

**Comment by orklah** [comment] 2022-02-03 14:31
@simPod see https://github.com/vimeo/psalm/issues/7568#issuecomment-1029047668. It was always rejected by Matt, I don't see us implementing that now. I'll close this issue

**Closed by orklah** 2022-02-03 14:31 UTC
