### ISSUE TITLE
Promote assertions on every element of the array to array type itself

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#988] opened 2018-09-09 01:46 UTC
https://getpsalm.org/r/ee49f7ec29
```php
<?php
  /** @param void ...$_p */
  function type(...$_p): void {}

  $a = [1, "a"];
  foreach ($a as $item) {
    assert(is_int($item));
    type($item); // int, as expected
  }
  type($a); // expected int[], (int|string)[] inferred
```
**Expected**: after the loop, Psalm could be sure `$a` is `int[]`
**Actual**: `$a` remains `(int|string)[]`

Could apply to `@psalm-assert`ed types as well. Probably only safe with arrays, as there's no guaranties Iterators would return same values if rewound and iterated again.

**Comment by muglug** [comment] 2018-09-09 15:27
Essentially a dupe of https://github.com/vimeo/psalm/issues/649

**Closed by muglug** 2018-09-09 15:27 UTC
