### ISSUE TITLE
Docblock assertions for unions doesn't work properly

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#8453] opened 2022-09-02 20:21 UTC
Probably related to #8421

https://psalm.dev/r/d6d343f91e
**Expected**: `non-empty-lowercase-string|int<1, 10>`
**Got**: `non-empty-lowercase-string`

https://psalm.dev/r/b8271ad72d
**Expected**: `int<1, 10>`
**Got**: `non-empty-lowercase-string` and an error `int does not contain non-empty-lowercase-string`

**Comment by AndrolGenhald** [comment] 2022-09-05 15:19
Duplicate of #5939, hoping to fix this next year along with a significant type system overhaul.

**Closed by AndrolGenhald** 2022-09-05 15:19 UTC
