### ISSUE TITLE
php notices 'Uninitialized string offset: 0' in the recent release

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#3354] opened 2020-05-12 16:43 UTC
with vimeo/psalm (3.11.4) we start seeing php warnings which in the end make our CI build-pipeline error.

see
```

Run vendor/bin/psalm --show-info=false --shepherd --diff --output-format=checkstyle | cs2pr
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 469 (12%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 469 (25%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 469 (38%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 240 / 469 (51%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 300 / 469 (63%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 360 / 469 (76%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░E░░░░░░░░░░░░░░░░░░░░░░░░ 420 / 469 (89%)
E░░░░░░░░PHP Notice:  Uninitialized string offset: 0 in /home/runner/work/redaxo/redaxo/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php on line 69
PHP Notice:  Uninitialized string offset: 0 in /home/runner/work/redaxo/redaxo/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php on line 69
PHP Notice:  Uninitialized string offset: 0 in /home/runner/work/redaxo/redaxo/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php on line 69
```

within this github action build: https://github.com/redaxo/redaxo/runs/667802698

**Comment by staabm** [comment] 2020-05-12 16:45
this notices did not show up and similar builds 2 days ago with psalm 3.11.2:

https://github.com/redaxo/redaxo/runs/659427571

**Comment by muglug** [comment] 2020-05-12 17:00
I'm unable to reproduce locally with that repo, but I added a proper exception in master to make it possible to nail down the culprit.

**Comment by staabm** [comment] 2020-05-12 17:30
Hmm just tried with latest dev-master and cannot repro anymore:

https://github.com/redaxo/redaxo/pull/3612

Maybe its related to result-caching

**Comment by muglug** [comment] 2020-05-12 18:00
Well, the exception's there now if this happens in the future

**Comment by muglug** [comment] 2020-05-12 18:05
I'm going to close this, as the precise issue (a notice) can no longer occur

**Closed by muglug** 2020-05-12 18:05 UTC

**Comment by staabm** [comment] 2020-05-12 19:34
@muglug related: why are these php-notices send out on stdout.. those should be printed on stderr, right?

**Comment by staabm** [comment] 2020-05-12 19:35
would you accept something like `ini_set('display_errors', 'stderr');` ?

**Comment by staabm** [comment] 2020-05-12 19:41
https://github.com/vimeo/psalm/pull/3355

**Comment by muglug** [comment] 2020-05-15 14:19
This should also now be prevented in the type system by 111303d
