### ISSUE TITLE
Support for splat operator (...$variable)

### ISSUE THREAD

**Issue by tomtomau** [vimeo/psalm#567] opened 2018-03-11 05:56 UTC
I'm using `0.3.93` with PHPUnit 6.5.7 and faced with something like below:

```   
$myMock = $this->createMock(CoolClass::class);
$myMock
    ->expects(self::once())
    ->method('foobar')
    ->with($arg1, $arg2);
```

Specifically, Psalm reports errors on the `->with(..$arguments)` call:
```
Argument 1 of PHPUnit\Framework\MockObject\Builder\InvocationMocker::with cannot be mixed, expecting array<mixed, mixed>
```

Where the with method source code seen in PHPUnit:

```
    /**
     * @param array ...$arguments
     *
     * @return InvocationMocker
     *
     * @throws RuntimeException
     */
    public function with(...$arguments)
    {
        // ...
    }
```

It seems to me as if Psalm doesn't comprehend `@param` call appropriately and thinks that $arguments should truly be an array?

I'm just trying to work out if my assumption is correct - at this stage, I'm considering dialing down Psalm on test suite code anyway.

**Comment by muglug** [comment] 2018-03-11 06:02
Psalm interprets `@param array ...$arguments` as equivalent to
```php
public function with(array ...$arguments) {
```
and expects each arg to be an array.

**Comment by muglug** [comment] 2018-03-11 06:06
(this is by design)

> I'm considering dialing down Psalm on test suite code anyway.

Yeah, you may want to. It‘s come in useful for things like checking that PHPUnit `@dataProvider` functions don‘t have duplicate array keys.

**Comment by tomtomau** [comment] 2018-03-11 06:12
Thanks for your prompt reply!

So to be clear, there's not great support for the splat operator?

**Comment by JanTvrdik** [comment] 2018-03-11 10:10
@tomtomau The PHPDoc is wrong, it's should be `@param mixed ...$arguments`. There used to be for a long time a [bug in PhpStorm](https://youtrack.jetbrains.com/issue/WI-29429) which unfortunately caused a lot of confusion to people with how the variadic PHPDoc should be written properly. This bug should be fixed in current EAP but I haven't tested it myself.

**Comment by muglug** [comment] 2018-03-11 13:43
@JanTvrdik thanks for the explanation! That also explains the last comment on https://github.com/phan/phan/issues/461 (which was fixed [here](https://github.com/phan/phan/pull/523) by @TysonAndre)

**Closed** 2018-03-11 14:07 UTC

**Comment by tomtomau** [comment] 2018-03-11 22:17
Thanks for the help folks!
