### ISSUE TITLE
UnusedPsalmSuppress scans vendor ignoring ignoreFiles

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#5302] opened 2021-03-01 16:29 UTC
I have enabled `UnusedPsalmSuppress` through `findUnusedPsalmSuppress="true"`

I have vendor excluded

```xml
    <projectFiles>
        ...
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
```

However, it reports error from vendor still:

> ERROR: UnusedPsalmSuppress - vendor/myclabs/php-enum/src/Enum.php:65:33 - This suppression is never used (see https://psalm.dev/207)

**Comment by cougargit** [comment] 2021-07-02 06:32
I can confirm the same behavior.

**Comment by orklah** [comment] 2021-08-07 12:40
closing this as duplicate of https://github.com/vimeo/psalm/issues/5356

**Closed by orklah** 2021-08-07 12:40 UTC
Labels: bug
