### ISSUE TITLE
Intersection Types In Throws Causes Error

### ISSUE THREAD

**Issue by XedinUnknown** [vimeo/psalm#6940] opened 2021-11-18 06:22 UTC
## The Symptoms
When [using][throws-example] intersection types in the `@throws` tag on 0fbf515, [Psalm crashes with the following output][psalm-error]:

> Analyzing /app/src/PipeMiddleware.php
> Uncaught InvalidArgumentException: Could not get class storage for dhii\pipe\dispatchexceptioninterface&runtimeexception in /app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:43

Unable to reproduce in [sandbox example][sandbox-example]. But either way, it thinks that `A&B` is one type, and doesn't seem to actually check `A` or `B`.

## Remarks
Changing intersection to union `|` allows me to go around the problem temporarily.

[psalm-error]: https://github.com/Dhii/pipe/runs/4247656107?check_suite_focus=true#step:8:7
[throws-example]: https://github.com/Dhii/pipe/blob/0.1.x/src/PipeInterface.php#L26
[sandbox-example]: https://psalm.dev/r/ce12bc2143

**Comment by orklah** [comment] 2021-11-18 22:02
This is basically a duplicate of https://github.com/vimeo/psalm/issues/3621. Psalm does not support intersection in throws yet. I think the explanation for the different error is that there is namespaces involved here and Psalm fails to resolve a class in there

**Closed by orklah** 2021-11-18 22:02 UTC
