### ISSUE TITLE
Cannot install PSALM

### ISSUE THREAD

**Issue by mabalashov** [vimeo/psalm#5766] opened 2021-05-14 11:51 UTC
Hello,

I found the following issue. You have the next line in [documentation](https://psalm.dev/docs/running_psalm/installation/):
```
wget https://github.com/vimeo/psalm/releases/latest/download/psalm.phar
chmod +x psalm.phar
./psalm.phar --version
```

But actually, this link goes nowhere, it returns 404

Because the phar package was not built for the last version 4.7.2

The link on previous version works fine:
```
https://github.com/vimeo/psalm/releases/download/4.7.1/psalm.phar
```

It is important because someone can use this link in dockerfile (even if it is not a good practice) and after some rebuild, the psalm will not work in the container

**Comment by weirdan** [comment] 2021-05-14 11:53
Duplicate of #5703

**Closed by weirdan** 2021-05-14 11:53 UTC
