### ISSUE TITLE
feature request about annotating arrays

### ISSUE THREAD

**Issue by max-matiukhin** [vimeo/psalm#859] opened 2018-07-03 12:51 UTC
Hi
Let suppose I have an array like 
```
array{id: int, name: string, email: string, ...}
```
In the real project this type may be used in a lot of places. Also eventually this structure may be updated and we will have to update all these annotations.
It would be great if we could create an alias to such types somewhere (some stub-file) and then use this alias through out the code?
Something like:
```
@psalm-type-alias _user array{id: int, name: string, email: string, ...}
```
and then use this alias in the annotations: @psalm-param _user $parameter
Probably aliases will need some prefix to distinguish them from normal classes like underscore in my example

These aliases could been used not only for arrays, but for any types (closures, union types etc)

Thanks

**Comment by muglug** [comment] 2018-07-03 12:54
Dupe of https://github.com/vimeo/psalm/issues/18 (earliest open issue) but good reason to add the functionality

**Closed by muglug** 2018-07-03 12:54 UTC

**Comment by muglug** [comment] 2018-07-16 14:16
> It would be great if we could create an alias to such types somewhere (some stub-file) and then use this alias through out the code?

Unfortunately the solution I chose requires that the types be added within the file itself: https://getpsalm.org/r/c9412db1ba

**Comment by weirdan** [comment] 2020-06-13 18:22
> Unfortunately the solution I chose requires that the types be added within the file itself

With recently added `@psalm-import-type` this limitation is lifted.
