### ISSUE TITLE
Class constant does not recognize result of bit shift as integer

### ISSUE THREAD

**Issue by mpesari** [vimeo/psalm#3075] opened 2020-04-05 23:18 UTC
https://psalm.dev/r/e8cbe00b06

It should recognize it as int, right?

**Comment by JoshuaBehrens** [comment] 2020-05-21 15:32
I can add a new case which suffers from the same bug I assume:
```php
<?php

class A
{
    public const Z = 'foobar';

    public function getStaticString(): string
    {
        // MixedReturnStatement
        return static::Z;
    }

    public function getSelfString(): string
    {
        // no MixedReturnStatement
        return self::Z;
    }
}
```

**Comment by weirdan** [comment] 2020-05-21 17:32
> I can add a new case which suffers from the same bug I assume:

This is not a bug. Since you're accessing the constant with `static`, and the class is not final one could extend the class and violate type constraints: 
psalm.dev: https://psalm.dev/r/a3519bc8cf
3v4l.org: https://3v4l.org/DHOLt - showing the error Psalm prevents from happening.

**Comment by JoshuaBehrens** [comment] 2020-05-21 17:41
@weirdan you are right. I tend to mixup static and self. Sorry for disturbing this issue 😖

**Comment by muglug** [comment] 2020-11-30 04:08
Fixed by @orklah

**Closed by muglug** 2020-11-30 04:08 UTC
Labels: bug
