### ISSUE TITLE
Intersection generic types & deep nested array structures

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#2781] opened 2020-02-10 09:51 UTC
## Background

When working with squishy API like `json_decode()`, we often write code like following:

```php

        $body = json_decode(
            $response->getBody()
                ->__toString(),
            true
        );

        Assert::isMap($body);
        Assert::keyExists($body, 'data');

        $data = $body['data'];

        Assert::isMap($data);
        Assert::keyExists($data, 'ids');

        $ids = $data['ids'];

        Assert::isList($ids);
        Assert::minCount($ids, 1);

        $id = $ids[0];

        Assert::integer($id);

        return $id;
```

The above is a mine-field of assertions, but it does indeed verify that `$body['data']['ids'][0]` exists.

In order to simplify things, I wanted to write a utility that verifies this type-level structure directly:

```php
Assert::matchesShape(
    $input,
    ['data' => ['ids' => [123]]
);

return $input['data']['ids'][0];
```

To do that, attempted to use a `@psalm-assert` approach, but psalm seems to discard any `array`-like types when restricting parameter types: 

https://psalm.dev/r/47d4290de5

It already rejects `$a` as `array`: 

```
INFO: MixedArrayAccess - 20:10 - Cannot access array value on mixed variable $a['b']
```

If I specify an `&array{b: array{c: string}}` explicitly, it rejects that, stating that an intersection between an `object` and an `array` type is being performed in a type declaration:

https://psalm.dev/r/64655bf105

Same if all templated types specify `@psalm-param SomeType of array`: https://psalm.dev/r/ae6040bada

**Comment by weirdan** [comment] 2020-02-10 11:49
I think proper way to address this would be to run a JSON schema validator on the incoming JSON and then have a plugin that provides the types to psalm based on the schema applied.

**Comment by Ocramius** [comment] 2020-02-10 11:59
@weirdan doesn't apply to just JSON, but to any incoming data structure (stored data, de-serialized data, xml, json, binary, yaml, etc.)

Effectively, we already have the mechanisms, just need to see if it's possible to apply the restriction with generic types and complex types.

**Comment by muglug** [comment] 2020-02-11 01:18
it seems like you're really asking for something like

```php
Assert::matchesType(
    $input,
    'array{a: string, b: int}'
);
```

with a signature for `matchesType` like

```php
/**
 * @template TType as string
 * @param mixed $input
 * @param TType $expected_type
 * @psalm-assert has-type<TType> $input
 */
public static function matchesType($input, string $expected_type) {
    ...
}
```

That's the only proper way I can see that would do exactly what you want.

**Comment by muglug** [comment] 2020-02-11 01:38
Hack has something similar at https://github.com/hhvm/type-assert (created by @fredemmott)

There's also https://github.com/hamlet-framework/type by @vasily-kartashov which aims to validate types expressed either in object form or as a string to be parsed.

**Comment by Ocramius** [comment] 2020-02-11 06:18
@muglug I'm mostly just wanting to align the type of two complex variables, not to build a custom DSL based on stringy types (much riskier, when used at runtime).

Given that the type system in psalm already goes this way, correcting the intersection logic for templated types to also consider `array` (I know it won't work with object-like) should work.

I just realized that this is pretty much like #2105 and #2115

**Comment by muglug** [comment] 2020-02-11 15:48
> I'm mostly just wanting to align the type of two complex variables

The problem is that Psalm types things as specifically as possible – it'll try and match the array you pass it exactly (including string/int values).

**Comment by muglug** [comment] 2020-02-12 03:20
Going to close this, as I don't think there's an obvious path forward

**Closed by muglug** 2020-02-12 03:20 UTC

**Comment by Ocramius** [comment] 2020-02-12 08:38
Same rationale as #2105? Are array intersections not feasible with the current design?
