### ISSUE TITLE
False condition contradiction with match statements matching enum values

### ISSUE THREAD

**Issue by cseufert** [vimeo/psalm#8849] opened 2022-12-06 03:49 UTC
Example
```php
<?php

enum A: string
{
  case I = 'I';
  case E = 'E';
}

function test(string $arg):int {
    return match ($arg) {
        A::E->value=> 1,
        A::I->value => 2,
      };
}
```

**Comment by cseufert** [comment] 2022-12-06 03:49
https://psalm.dev/r/35fbdd5cec

**Comment by weirdan** [comment] 2022-12-06 05:19
Duplicate of #8812

**Closed by weirdan** 2022-12-06 05:19 UTC
