### ISSUE TITLE
Variadic parameter handling 

### ISSUE THREAD

**Issue by drupol** [vimeo/psalm#5508] opened 2021-03-29 13:56 UTC
Hello,

This example show the issue: https://psalm.dev/r/6216fb4626

There should not be any `ERROR: DuplicateArrayKey - 25:61 - String keys are not supported in unpacked arrays`.

**Comment by AndrolGenhald** [comment] 2021-03-29 14:05
See #5500 #5503.
@weirdan Maybe I should have documented this somewhere?

**Comment by weirdan** [comment] 2021-03-29 15:09
Duplicate of #5500

**Closed by weirdan** 2021-03-29 15:09 UTC

**Comment by weirdan** [comment] 2021-03-29 15:10
@drupol you're third today to report this. I wonder what's going on :thinking:

**Comment by AndrolGenhald** [comment] 2021-03-29 15:13
@weirdan 4.7.0 was released with #5455 11 hours ago. I'd add documentation somewhere, but I'm not really sure if it would help, I think the new behavior is just unexpected because named arguments is still pretty new.

**Comment by weirdan** [comment] 2021-03-29 15:15
@AndrolGenhald https://github.com/vimeo/psalm/blob/master/docs/running_psalm/issues/DuplicateArrayKey.md is linked from the message, and it'll be updated automatically on psalm.dev, so it's best to document it there.

**Comment by drupol** [comment] 2021-03-29 20:19
> @drupol you're third today to report this. I wonder what's going on thinking

Sorry mate for this, and thanks for letting me know where I was wrong.
