### ISSUE TITLE
Templated throw type

### ISSUE THREAD

**Issue by trowski** [vimeo/psalm#5692] opened 2021-04-29 18:45 UTC
We are looking at templating a placeholder with the exception type that can be used to fail the placeholder, but found we weren't able to use the template type in a `@throws` declaration.

https://psalm.dev/r/bf2dcf5af3

**Comment by whizsid** [comment] 2021-05-21 19:53
+1

**Comment by weirdan** [comment] 2021-05-24 18:17
Duplicate of #3784

**Closed by weirdan** 2021-05-24 18:17 UTC
Labels: enhancement
