### ISSUE TITLE
False error on casting to object for methods that take stdClass

### ISSUE THREAD

**Issue by jpresutti** [vimeo/psalm#8198] opened 2022-06-29 13:30 UTC
Casting an array to an object creates a stdClass according to https://www.php.net/manual/en/language.types.object.php#language.types.object.casting -- However, Psalm reports this as an ArgumentTypeCoercion error. 

See https://psalm.dev/r/d36d3682f8

**Comment by AndrolGenhald** [comment] 2022-06-29 14:21
Duplicate of #8187.

**Closed by AndrolGenhald** 2022-06-29 14:21 UTC
