### ISSUE TITLE
Uncaught Exception: InvalidArgumentException Could not get class storage for opensslcertificate

### ISSUE THREAD

**Issue by imdhemy** [vimeo/psalm#8661] opened 2022-11-05 07:34 UTC
The `openssl_x509_verify` function throws the following exception when scanned with psalm:

```
░Uncaught Exception: InvalidArgumentException Could not get class storage for opensslcertificate
Emitted in vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:46

.
.
.

(Psalm 4.29.0@7ec5ffbd5f68ae03782d7fd33fff0c45a69f95b3 crashed due to an uncaught Throwable)

```

| Q | A |
| --- | --- |
| PHP version | 7.4 |
| Installed PHP | 8.1 |
| With cache | happens with `--no-cache` |
| Psalm | 4.29.0 |
| Reproduce link | https://psalm.dev/r/bbaf73ccc1 |

**Comment by orklah** [comment] 2022-11-06 09:34
Could you check if you also have the issue with the beta version of Psalm 5 please?

**Comment by imdhemy** [comment] 2022-11-06 13:03
Yes, Psalm 5 beta version has the same issue.

**Comment by orklah** [comment] 2022-11-06 20:07
This issue is actually a duplicate of https://github.com/vimeo/psalm/issues/7100 that I forgot about. There's a few interesting facts there so I'll close this one

**Closed by orklah** 2022-11-06 20:07 UTC

**Comment by orklah** [comment] 2022-11-06 20:25
Also, this should be fixed by https://github.com/vimeo/psalm/pull/8677

**Comment by imdhemy** [comment] 2022-11-06 21:05
It works 🎉... Thanks a lot!
