### ISSUE TITLE
Inline declaration of variable type

### ISSUE THREAD

**Issue by joehoyle** [vimeo/psalm#3795] opened 2020-07-10 09:41 UTC
Leading on from #3794, I sometimes find myself want to explicitly declare a variable's type at some point in the control flow. It might be that the Psalm types can't quite express the logic, but I _know_ a type of a var all the same.

It would be useful to be able to declare / update a variable type at any point by doing `/** @var string $myvar */`. Currently I have to do a workaround like this:

```php
$myvar = some_func();

if ( $myvar === 'bye' ) {
    exit;
}

// I know the type of $myvar is now int
/** @var int */
$myvar = $myvar;
```

It would be a lot better to be able to do:

```php
$myvar = some_func();

if ( $myvar === 'bye' ) {
    exit;
}

// I know the type of $myvar is now int
/** @var int $myvar */
```

**Comment by muglug** [comment] 2020-07-10 16:18
dupe of https://github.com/vimeo/psalm/issues/1916

**Closed by muglug** 2020-07-10 16:18 UTC
