### ISSUE TITLE
Resource is a reserved word

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1644] opened 2019-05-16 05:09 UTC
Cannot reproduce it on psalm.dev, unfortunately. What I'm seeing is

```
ReservedWord - src/ResourceType.php:8:7 - 'resource' is a reserved word
class ResourceType extends Type
```

**Comment by muglug** [comment] 2019-05-16 17:38
I can't reproduce in your repo

**Comment by vasily-kartashov** [comment] 2019-05-16 22:45
You can still see it when referencing 3.2.12 explicitly and removing the nuclear option: https://github.com/hamlet-framework/type/blob/3e31be97f5b9a82fd0743f4925aaf1e82270445d/psalm.xml#L19 

But it's gone on the latest dev-master so I suspect it's related to this caching issue: https://github.com/vimeo/psalm/issues/1646

**Comment by muglug** [comment] 2019-05-16 23:07
Huh ok. Closing, then. Feel free to reopen if it appears again.

**Closed by muglug** 2019-05-16 23:07 UTC
