### ISSUE TITLE
Use psalm-type as generic parameter

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#4804] opened 2020-12-07 22:15 UTC
Example: https://psalm.dev/r/c7fb0aa262

Is it possible to define type and use it as generic parameter? Right now, I have to duplicate things:

```php
/**
 * @implements HasAggregateValuesInterface<array{nr_of_assigned_addresses?: ?int}, RouteAggregatesCollection>
 */
class Route implements HasAggregateValuesInterface
{

    /** @use HasAggregateValuesTrait<array{nr_of_assigned_addresses?: ?int}, RouteAggregatesCollection> */
    use HasAggregateValuesTrait;
}
```

**Comment by weirdan** [comment] 2020-12-07 23:32
Duplicate of #4240

**Closed by weirdan** 2020-12-07 23:32 UTC
