### ISSUE TITLE
Psalm assert doesn't seem to support the syntax `CLASS:CONSTANT_*`

### ISSUE THREAD

**Issue by aszenz** [vimeo/psalm#6936] opened 2021-11-17 12:11 UTC
Psalm assert doesn't refine the type in the second example

https://psalm.dev/r/23052274c0

**Comment by aszenz** [comment] 2021-11-17 12:26
It also doesn't seem to support CLASS::CONST syntax

https://psalm.dev/r/1268c7d6a6

**Comment by weirdan** [comment] 2021-11-17 12:30
Duplicate of #6300

**Closed by weirdan** 2021-11-17 12:30 UTC
