### ISSUE TITLE
Psalm tracks more specific type through generic assignment

### ISSUE THREAD

**Issue by aidantwoods** [vimeo/psalm#1931] opened 2019-07-10 09:06 UTC
Related to #1886, Psalm doesn't truly internally represent T as the resolves upcasted param: https://psalm.dev/r/9287453536

I would expect Psalm to say it expects `Foo<array<array-key, mixed>>` here, instead it tracks the struct-like array.

**Comment by muglug** [comment] 2019-07-10 12:59
This is really a dupe of #1927, but I'll leave it open until I've fixed that

**Comment by aidantwoods** [comment] 2019-07-10 16:17
Thanks :) I did see that one, but couldn't see for sure whether it was the same issue so thought I'd open this one anyway.

**Closed** 2019-07-10 17:49 UTC
