### ISSUE TITLE
Enums and @template problem

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#7836] opened 2022-04-02 04:12 UTC
https://psalm.dev/r/1cb8d6e343

**Comment by AndrolGenhald** [comment] 2022-04-02 04:44
Hmm, it seems Psalm currently considers enum cases to be subtypes of their enum, but according to [this](https://3v4l.org/2umBg) they're also _sort of_ equal to the enum in certain ways. I _think_ your usage should be allowed, but I'm not familiar enough with PHP's enums to be sure. Do you have any idea @orklah?

The cause of the problem is that templates are invariant by default to prevent the infamous meowing dog, you can work around this problem for now by using [`@template-covariant`](https://psalm.dev/r/dca05c8a45) if that works for your case.

**Comment by orklah** [comment] 2022-04-02 22:43
I'm not much of an expert on enum myself!

Still stuck on 7.4 at work, so I haven't had occasions to try those :p

**Comment by vudaltsov** [comment] 2022-04-02 23:04
@AndrolGenhald , I understand what you are talking about. But I don't think that enum's cases should follow this logic, since it's not inheritance.

I think, they are more like strings and literals:

https://psalm.dev/r/f0252293b5

**Comment by AndrolGenhald** [comment] 2022-04-02 23:47
Actually I'm afraid this is a problem, we'll need automatic upcasting to prevent [this](https://psalm.dev/r/c821b51194).

The string example seems to have a [special case upcast](https://psalm.dev/r/befe4d717d) already implemented, that's interesting. Maybe that'll be a useful place to start with the generic upcasting implementation.

I'm going to close this as a duplicate of #7675 since that's the actual issue, I'll try to prioritize it soon. In the meantime you'll have to [work](https://psalm.dev/r/9fe1265d71) [around](https://psalm.dev/r/dca05c8a45) it [somehow](https://psalm.dev/r/936d652249).

**Closed by AndrolGenhald** 2022-04-02 23:47 UTC
Labels: bug, templates, enum

**Comment by vudaltsov** [comment] 2022-04-02 23:50
Thank you!
