### ISSUE TITLE
endless loop return type

### ISSUE THREAD

**Issue by timglabisch** [vimeo/psalm#4380] opened 2020-10-21 09:03 UTC
would be cool if psalm could unterstand, that this is valid.

https://psalm.dev/r/b65d92985e

**Comment by orklah** [comment] 2020-11-26 22:39
duplicates https://github.com/vimeo/psalm/issues/4245

**Comment by weirdan** [comment] 2020-11-27 00:39
Duplicate of #4245

**Closed by weirdan** 2020-11-27 00:39 UTC
