### ISSUE TITLE
Constructor property promotion + @var + @template fails

### ISSUE THREAD

**Issue by rarila** [vimeo/psalm#8252] opened 2022-07-13 11:36 UTC
Psalm fails to handle ``@var`` definitions when a template is defined and used:

https://psalm.dev/r/9c1dcef0a7

Same code without constructor property promotion works:

https://psalm.dev/r/360d5f1a9e

Also no problem with [PHPStan](https://phpstan.org/r/8ca8ce10-8c03-442a-8ba9-05f42708e268).

Using ``@param`` in the constructor seems to be a workaround:

https://psalm.dev/r/5cf6c1e9d2

**Comment by AndrolGenhald** [comment] 2022-07-13 16:04
Duplicate of #7919.

**Closed by AndrolGenhald** 2022-07-13 16:04 UTC
