### ISSUE TITLE
psalm loses track of variable type inside a switch statment when using `@var`

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#5494] opened 2021-03-28 11:38 UTC
correct: https://psalm.dev/r/c97a88395d
false: https://psalm.dev/r/5dc0fe47be
false: https://psalm.dev/r/f2f527484f

all examples give above have the same behavior, but only one of them has the correct/expected output.

**Comment by muglug** [comment] 2021-03-28 14:42
Closing as not a bug, because in all the failing scenarios `false` is a valid argument

**Closed by muglug** 2021-03-28 14:42 UTC

**Comment by AndrolGenhald** [comment] 2021-03-29 13:23
@muglug Am I missing something? It looks like this is valid code where psalm infers the incorrect type: https://3v4l.org/96NYq https://psalm.dev/r/b6448def70

This might be better practice anyway though, and it does seem to work correctly: https://3v4l.org/cC86q https://psalm.dev/r/eb208b0cb4
Original example: https://psalm.dev/r/92bdc7be90
