### ISSUE TITLE
`unset($var['field'])` should remove the corresponding field of ObjectLike

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#454] opened 2018-01-19 21:12 UTC
Low priority because it's used infrequently.

Expected: Warn about $x['a'] being undefined.

```php
<?php

function testempty() : void {
    $x = ['a' => 'value', 'b' => 'value'];
    unset($x['a']);
    echo $x['a'];  // type for $x is still array{a:string, b:string}
}
```

**Comment by muglug** [comment] 2018-01-19 21:15
Dupe of #455 

I know it predates it by around a minute, but I'm slow at typing.

**Closed by muglug** 2018-01-19 21:15 UTC
