### ISSUE TITLE
Warn if psalm-suppress doesnt actually suppress a error

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#2033] opened 2019-08-18 07:03 UTC
when using `@psalm-suppress` on a line which doesnt emit the actual error the suppress is trying to omit, it would be cool if psalm would emit a warning/error because the suppress won't do what the author is trying to achieve.

e.g. phpstan shows warnings for errors you define to be ignored in your config file, but actually dont occur.

**Comment by muglug** [comment] 2019-08-18 15:19
Duplicate of https://github.com/vimeo/psalm/issues/1444

**Closed by muglug** 2019-08-18 15:19 UTC

**Comment by muglug** [comment] 2019-08-18 20:33
And that's now fixed
