### ISSUE TITLE
Could not intersect two array shapes

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#7909] opened 2022-04-28 16:34 UTC
https://psalm.dev/r/c2e2af5818

**Comment by klimick** [comment] 2022-04-28 16:39
May be intersection doesn't work only with psalm-alias.
https://psalm.dev/r/3af7cbf3d7

**Comment by orklah** [comment] 2022-04-28 17:24
Yeah, we're missing something to support that. I believe we already have an issue  for this

**Comment by AndrolGenhald** [comment] 2022-04-28 17:59
Duplicate of #5148.

**Closed by AndrolGenhald** 2022-04-28 17:59 UTC
Labels: enhancement
