### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: Could not get class storage for runtimeexception 

### ISSUE THREAD

**Issue by parktrip** [vimeo/psalm#1860] opened 2019-06-28 07:13 UTC
I tried for the first time psalm on one of my zf2 project.
when I run psalm, I have this error

```
Fatal error: Uncaught InvalidArgumentException: Could not get class storage for runtimeexception in vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStorageProvider.php:46
Stack trace:
#0 vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassLikeAnalyzer.php(312): Psalm\Internal\Provider\ClassLikeStorageProvider->get('runtimeexceptio...')
#1 vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\Call\NewAnalyzer.php(278): Psalm\Internal\Analyzer\ClassLikeAnalyzer::checkFullyQualifiedClassLikeName(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'RuntimeExceptio...', Object(Psalm\CodeLocation), Array, false)
#2 vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(377): Psalm\Internal\Analyzer\Statements\Expression\Call\NewAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\New_), Object(Psalm\Context))
#3 vendor\vimeo\psalm\src\Psalm\In in D:\www\melliol\hoa\vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStorageProvider.php on line 46
```

this runtimeexception is located in [public/index.php line 25](https://github.com/zendframework/ZendSkeletonApplication/blob/master/public/index.php#L25) from the zf skeleton app

if I remove the line, psalm run without fatal error. Looks strange as RunTimeException seems to be a valid php exception.

I am using php 7.1.26 with the latest version of psalm

regards

**Comment by muglug** [comment] 2019-06-28 12:05
Sorry - does it work with the previous version of Psalm (3.4.5)?

**Comment by parktrip** [comment] 2019-06-28 12:22
Sorry, I switched to something else in the meantime, I will try again next week

**Comment by muglug** [comment] 2019-06-28 12:57
The problem is basically that Psalm can not conceive of a world in which the Application class does not exist, so it refuses to scan the contents of the if block. Until I release a fix (likely on Monday) a solution would be to nest the instantiation of RunTimeException inside a function, but outside the if block.

**Comment by muglug** [comment] 2019-06-28 12:58
The problem is basically that Psalm can not conceive of a world in which the Application class does not exist, so it refuses to scan the contents of the if block. Until I release a fix (likely on Monday) a solution would be to nest the instantiation of RunTimeException inside a function, but outside the if block.

**Comment by parktrip** [comment] 2019-06-28 13:16
don't know if it helps but I have tried with v3.4.5 and I have the same issue

**Comment by muglug** [comment] 2019-06-28 14:18
Should be fixed in `dev-master` - I'll tag a release over the weekend, most likely

**Closed** 2019-06-28 14:18 UTC
Labels: bug

**Comment by muglug** [comment] 2019-06-28 15:34
This is now in a release - 3.4.7 - it's a serious-enough bug that I didn't want anyone else to encounter it. Let me know on Monday if it doesn't work, and thanks for ticketing!

**Comment by parktrip** [comment] 2019-07-01 06:27
dear @muglug , I have tried this morning and no fatal error anymore. Thank you for your prompt fix. have a nice week
