### ISSUE TITLE
Psalm tries to create cache directory when run with `--no-cache`

### ISSUE THREAD

**Issue by AndrolGenhald** [vimeo/psalm#8138] opened 2022-06-21 21:21 UTC
I ran into this when running under docker as non-root: `Could not create cache directory: //.cache/psalm/0256f207edf2e8d3d5f36b8d84c501432f54d6f5`

Testing further outside of docker, it looks like Psalm creates the cache directory and a subdirectory, but then doesn't put anything there. These directories shouldn't be created when run with `--no-cache`.

**Comment by orklah** [comment] 2022-06-21 21:25
duplicate of https://github.com/vimeo/psalm/issues/4267 :)

**Closed as completed by orklah** 2022-06-21 21:25 UTC
Labels: bug
