### ISSUE TITLE
Psalter for MissingPropertyType issue

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#3702] opened 2020-06-28 14:41 UTC
Hi,

It doesn't seem that Psalter support fixes for MissingPropertyType. Is that something that was considered but discarded?

Thanks

**Comment by muglug** [comment] 2020-07-02 16:33
Dupe of https://github.com/vimeo/psalm/issues/435

**Closed by muglug** 2020-07-02 16:33 UTC
