### ISSUE TITLE
Callables with generic arg types are not supported

### ISSUE THREAD

**Issue by simPod** [vimeo/psalm#7529] opened 2022-01-30 15:25 UTC
This does work (https://psalm.dev/r/bd53c9d4d1)

```php
 * @psalm-type T callable(int[]):string
```

This does not (having `<>` as arg type)

https://psalm.dev/r/b0f597b1ba

```php
 * @psalm-type T callable(array<int>):string
```

_Related to https://github.com/vimeo/psalm/issues/7527 I guess_

**Comment by orklah** [comment] 2022-01-30 15:27
duplicate of https://github.com/vimeo/psalm/issues/6928

There were one or two tentative fix for now, but it didn't get further. It's a regex issue at the core

**Closed by orklah** 2022-01-30 15:27 UTC
