### ISSUE TITLE
Psalm incorrectly outputs an error when an interface method is in an abstract base class

### ISSUE THREAD

**Issue by twhiston** [vimeo/psalm#74] opened 2017-01-23 08:58 UTC
When running psalm over a class which has an abstract base class which implements an interface method I get an error.

(example shortened for clarity)

```
/**
 * Defines an interface for Field mapper plugin plugins.
 */
interface FieldMapperInterface  {

  public function getElasticType();

  public function getSupportedTypes();

}


/**
 * Base class for Field mapper plugin plugins.
 */
abstract class FieldMapperBase implements FieldMapperInterface {

  public function getElasticType() {
    return 'my_type';
  }

}

class Long extends FieldMapperBase {

  public function getSupportedTypes() {
    return ['integer'];
  }

}
```

will produce the error
ERROR: UnimplementedInterfaceMethod - modules/custom/elastic_search/src/Plugin/FieldMapper/Long.php:21 - Method Drupal\elastic_search\Plugin\FieldMapperInterface::getElasticType is not defined on class Drupal\elastic_search\Plugin\FieldMapper\Long

**Comment by muglug** [comment] 2017-01-23 14:28
Do you get this with latest dev-master?

**Comment by muglug** [comment] 2017-01-23 14:34
A similar issue was fixed in https://github.com/vimeo/psalm/commit/ba88cda18d992ae6a0febd4bec7758cf6f5a6d3b

**Comment by twhiston** [comment] 2017-01-23 18:34
unfortunately yes. I'm requiring dev-master and I'm at the latest version. I did see that closed issue but sadly I think this is an additional problem.

**Comment by muglug** [comment] 2017-01-23 20:42
Would you be able to share the files that produce this error?

I'm unable to reproduce when running on a single file (using the following PHP on https://getpsalm.org)

```php
<?php
interface I {
  public function foo();
  public function bar();
}
abstract class A implements I {
  public function foo() {
    return 'hello';
  }
}
class B extends A {
  public function bar() {
    return 'goodbye';
  }
}
```

**Comment by muglug** [comment] 2017-02-04 02:06
Closing unless there's more information

**Closed by muglug** 2017-02-04 02:06 UTC
Labels: more info needed
