### ISSUE TITLE
False positiv Static property not defined with Closure::bind

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#5551] opened 2021-04-01 08:01 UTC
I expect no error in
https://psalm.dev/r/34eab5a92d

I discover that psalm handle correctly this https://psalm.dev/r/470e3469a1, it may help to debug.

**Comment by weirdan** [comment] 2021-04-01 08:36
You can use `@psalm-scope-this` as a workaround: https://psalm.dev/r/c5c511ca0f

**Comment by VincentLanglet** [comment] 2021-04-01 10:14
> You can use `@psalm-scope-this` as a workaround: https://psalm.dev/r/c5c511ca0f

Unfortunately phpcs-fixer is transforming `/**` to `/*` when it's not a function doc. But that's another issue (https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5505)

Any idea where I should look in psalm code to implement the bug fix ?

**Comment by weirdan** [comment] 2021-04-01 11:45
In fact, I think, it's a duplicate of #913. [`ClosureAnalyzer`](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/ClosureAnalyzer.php) is likely where it needs to happen.

**Comment by muglug** [comment] 2021-04-04 13:44
Yeah, closing as duplicate of #913

**Closed by muglug** 2021-04-04 13:44 UTC

**Comment by VincentLanglet** [comment] 2021-04-04 17:27
I'd like to try to fix this.
Maybe you can help me ?

I discovered it works https://psalm.dev/r/51fb64c2ad with `$this::` but not `static::` or `$this->`, 

I assume I should work inside https://github.com/vimeo/psalm/blob/f07b6e675e706a05029d340ac07e4b701451568b/src/Psalm/Internal/Analyzer/ClosureAnalyzer.php#L63 ? Can you confirm it ?
