### ISSUE TITLE
DocblockTypeContradiction detecting string[]|string as only array<array-key, string>

### ISSUE THREAD

**Issue by linaori** [vimeo/psalm#8005] opened 2022-05-25 08:38 UTC
It doesn't matter if I do `@param string[]|string $fields` or `@param string|string[] $fields`, it always gets detected as `array<array-key, string>`

https://psalm.dev/r/f472932324

**Comment by kkmuffme** [comment] 2022-05-25 12:15
This error is correct. At the place where you check `!is_array` it's always an array already.

line 7/8 you check if it's string, and assign it to an array (string[] specifically).

**Comment by linaori** [comment] 2022-05-25 12:47
I can do `addWhere(false)` and it's neither an array or string and it would break my code if called. You would be correct if I could do `string|array $fields`, but I'm on 7.4.

**Comment by kkmuffme** [comment] 2022-05-25 14:02
can you please provide a psalm.dev example

**Comment by linaori** [comment] 2022-05-25 14:12
It's in the first post

**Comment by linaori** [comment] 2022-05-25 14:29
No that's not true, php doesn't enforce docblock types. I have no control over how this function is called because it's a re-usable package. If an end-user decides to call addWhere(false), it will happily receive the wrong type.

https://3v4l.org/k9aUJ

```php
<?php

/**
 * @param string[]|string $fields
 */
function addWhere($fields): void
{
    if (is_string($fields)) {
        $fields = [$fields];
    }

    var_dump($fields);
    
    if (! is_array($fields)) {
        throw new InvalidArgumentException('$field must be a string or array.');
    }

}

addWhere(false);
```

I can "fix" it by adding `/** @var mixed $fields */`, but imo psalm should infer that the actual type is `mixed` based on the signature. The docblock is only suggestive.

**Comment by AndrolGenhald** [comment] 2022-05-25 14:59
There's been discussion in slack before about having a way to make Psalm ignore certain param docblocks at library boundries, since the library can't enforce type checking by consumers. It sounds like PHPStan supports something like this, and it would be useful to have.

**Comment by AndrolGenhald** [comment] 2022-05-26 04:29
It turns out we do already have a [useDocblockTypes](https://psalm.dev/docs/running_psalm/configuration/#usedocblocktypes) config, but I think that might also disable using the docblock type when checking callers, which I don't think works well for the use cases I'm thinking of at least.

**Comment by ciaranmcnulty** [comment] 2022-05-26 07:43
> The docblock is only suggestive

The friction here is that this is fundamentally not how Psalm treats docblocks - if you put some type information in there it'll treat it as truth.

**Comment by kkmuffme** [comment] 2022-05-26 08:13
>That doesn't enforce docblock types, and there will probably always be parameter types in libraries that want additional checks because PHP type declarations can't always be as specific as docblock types (eg templates but also other things).

Not in real world usage, but for psalm it does. Psalm treats docblock types as strict types in all cases - if a type does not match the docblock, psalm will give an error. That is the purpose of static analysis with psalm.

As I originally said: this error is valid from a point of view of static analysis. If you don't want an error there use @psalm-suppress.
I am not sure what this issue is on about anymore. There's nothing that would make sense to change in psalm.

**Comment by AndrolGenhald** [comment] 2022-05-26 14:41
I think I'll go ahead and close this as a duplicate of #8017 since that's more clear about what the feature request actually is, and this issue reads more like an XY problem.

**Closed by AndrolGenhald** 2022-05-26 14:41 UTC
Labels: enhancement
