### ISSUE TITLE
DuplicateArrayKey - String keys are not supported in unpacked arrays

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#5514] opened 2021-03-29 20:35 UTC
https://psalm.dev/r/0cf78f15c0

Expect no error because `$parameters`'s key will be always an int.

**Comment by orklah** [comment] 2021-03-29 21:02
Duplicate of https://github.com/vimeo/psalm/issues/5508

In case of named arguments, $parameters keys will be strings

**Comment by snapshotpl** [comment] 2021-03-29 21:44
Ok, so it's possible to mark via phpdocs allow only int keys?

**Comment by AndrolGenhald** [comment] 2021-03-29 22:00
It's mentioned in the [documentation link](https://psalm.dev/docs/running_psalm/issues/DuplicateArrayKey/) for the issue now: use `@no-named-arguments`.

**Closed** 2021-03-29 22:51 UTC
