### ISSUE TITLE
Crash Enum Case Const Expression

### ISSUE THREAD

**Issue by timglabisch** [vimeo/psalm#10081] opened 2023-08-03 06:29 UTC
https://psalm.dev/r/6b2ec40b16

Psalm crashes when parsing a const expressions in enum cases.

```php
<?php
enum X: string {
    case BAR2 = Foo::SOME_CONST;
}
```

**Comment by weirdan** [comment] 2023-08-16 19:13
Duplicate of #8978

**Closed by weirdan** 2023-08-16 19:13 UTC
Labels: bug, causes crash, enum
