### ISSUE TITLE
Test suite fails on Windows

### ISSUE THREAD

**Issue by brayniverse** [vimeo/psalm#6449] opened 2021-09-07 07:47 UTC
I ran the test suite on Windows 10 using PHP 8.0 while working on #6418 and encountered the following errors.

![image](https://user-images.githubusercontent.com/945367/132305195-d29f4bfa-6f1d-4dce-a8e4-dc226e5225f2.png)
![image](https://user-images.githubusercontent.com/945367/132305285-4deb1532-2a97-4552-8ce5-ceead8a7bc60.png)

@weirdan said this about the errors:

> One appears to be symlink related (who knew Win can do symlinks?) and the other looks like composer internal issue, but this will need to be investigated further.

I'm not sure how to go about helping to solve these errors but if you need any more information I'm happy to help.

**Comment by orklah** [comment] 2021-09-07 11:00
I can confirm the symlink test fail on windows and PHP 8.0. However, the composer one is working on my end. It's probably due to how composer is installed on your machine.

I wonder what makes the symlink test pass on CI though...

**Comment by weirdan** [comment] 2021-09-07 11:20
That test is skipped based on some conditions that are not immediately obvious to me. Perhaps it never runs in GH CI.

**Comment by orklah** [comment] 2021-09-07 17:18
> That test is skipped based on some conditions that are not immediately obvious to me.

The test seems ready to accept a specific error
> symlink(): Cannot create symlink, error code(1314)

but what I get when I run the test is 
> unlink(C:\...\psalm\tests/fixtures/symlinktest/ignored/b): No such file or directory
and 
> symlink(): Permission denied

seems like the CI either fail the way it's intended or succeed so this is not an issue. Maybe we should just skip the whole test on windows...

**Comment by weirdan** [comment] 2021-09-07 20:23
> Maybe we should just skip the whole test on windows...

My thoughts exactly. Symlinks on NTFS, while technically possible, are a quite exotic feature known by a few and requiring elevated permissions (last time I checked, which is quite a while ago).

**Comment by orklah** [comment] 2021-09-07 21:36
ideally, we should maybe skip the other one with composer if we detect composer is not installed in standard way. This way contributors on windows would have a working test suite

**Comment by weirdan** [comment] 2024-02-25 13:11
The composer issue was fixed in 1.10: https://github.com/composer/composer/pull/9076

**Closed** 2024-02-25 13:34 UTC
Labels: Help wanted, Windows
