### ISSUE TITLE
@psalm-internal don't throw error when used for constructor

### ISSUE THREAD

**Issue by vjik** [vimeo/psalm#5841] opened 2021-05-27 13:47 UTC
See example: https://psalm.dev/r/93b9cb3533

**Comment by bdsl** [comment] 2021-05-27 14:39
`@internal` also doesn't throw error here. It works if you call the constructor directly by name. That's not a solution or even a usable workaround, but it shows that the issue is around tracking that `new` refers to the constructor.

https://psalm.dev/r/af0865496a

**Comment by bdsl** [comment] 2021-05-27 14:59
Maybe a useful workaround is to make the constructor private and introduce a named constructor (i.e. static method that returns an instance of self). That static method can then be marked as `@internal`, and used as the constructor.

**Comment by vjik** [comment] 2021-05-27 15:38
> Maybe a useful workaround is to make the constructor private and introduce a named constructor (i.e. static method that returns an instance of self). That static method can then be marked as `@internal`, and used as the constructor.

Yes, this solutions for my case.
But I would like to specify it for the constructor as well :)

**Closed** 2021-05-28 13:44 UTC
Labels: bug
