### ISSUE TITLE
Documentation: Document a list of Psalm's features in README or wiki

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#308] opened 2017-11-15 19:32 UTC
I don't see this in the wiki or README:

Currently available resources make it hard to find out what Psalm's features are:

- config.xsd, but that is just a list of issue types, and doesn't describe how the implementation works
- Release notes and commit history, but that's not in one place

**Comment by muglug** [comment] 2017-11-20 06:00
I plan to have proper documentation – potentially at getpsalm.org - in a fortnight or so.

Any things you think I should focus on? Off the top of my head:
 - a list of phpdoc annotations Psalm supports
 - a list of Psalm-specific docblock annotations, including `@template`
 - a plugin guide
 - autoloading
 - how Psalm interprets your code
   - array handling, including object-like arrays
   - handling of pass-by-reference variables
   - handling of logic flows and `ParadoxicalCondition`
   - maybe summarise [this blog post](https://medium.com/vimeo-engineering-blog/automated-type-inference-for-dynamically-typed-programs-6e79197e5420) I wrote

Also *maybe* a list of every issue, together with code that would trigger the issue. But don't hold me to that.

**Comment by muglug** [comment] 2017-11-20 06:01
cc @nickyr @erunion

**Comment by TysonAndre** [comment] 2017-11-20 06:55
Other ideas:

- Document phpdoc array support, including keyed arrays, `array<T>`, `array<K, T>` and `array{key: string}`
- Nullable shorthand support
- Documentation of config.xml options and what they do (E.g. extended `<!-- -->` comments in config.xsd). Something along the lines of this:

  ```xml
  <!-- Serializer controls the serialization format of the cache of ASTs. It can be set to igbinary to reduce disk usage and time needed for unserializing. -->
  <xs:attribute name="serializer" type="xs:string" />
  ```

  config.xml options seem to be hard to discover right now.
- Documentation of CLI options online (e.g. raw output of `--help`)

**Comment by erunion** [comment] 2017-11-20 14:25
@muglug I think that list is a good start.

**Comment by nickyr** [comment] 2017-11-20 14:32
> Also maybe a list of every issue, together with code that would trigger the issue. But don't hold me to that.

That would be super useful to people getting started with Psalm I think.

Should also talk about the different ways you can suppress issues or mark them as info (psalm.xml, function-level annotations, and in-line annotations) 

Tips on making psalm not complain too much when you are using an improperly typed library in your project would also be useful (for example, by extending the library classes and using @var annotations to type things correctly.)

**Comment by muglug** [comment] 2018-01-01 01:34
All issues are now documented in https://github.com/vimeo/psalm/blob/master/docs/issues.md

**Comment by nickyr** [comment] 2018-01-01 04:05
That's beautiful! 

I was looking around and thought this tool could be really helpful for generating this document from code: https://github.com/plaid/transcribe

What do you think about adding the docs to the issue class files and generating issues.md with that tool?

I might give this a try on my flight back to NJ tomorrow... no promises though because offline coding sucks.

**Comment by muglug** [comment] 2018-01-01 14:03
@nickyr I'd rather not have commented-out PHP in PHP – seems a little screwy. What I *would* like is a test that checks whether all issues are represented in the `issues.md`, and also checks the supplied reproducible code to ensure that Psalm emits the given issue.

There's something similar for checking that `config.xsd` accepts all issues: https://github.com/vimeo/psalm/blob/1608463b095ec2098d969bae2926751bc22166e6/tests/ConfigTest.php#L183-L217

**Comment by nickyr** [comment] 2018-01-01 16:44
I like your idea, but I think it would still be good to have the documentation come directly from the source code. For one thing, it would make it a lot easier for people contributing to the project.

And it's not really that screwy. Phpdoc supports it with the code tag: https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.example.pkg.html
Here's a nice example in the wild: https://github.com/thephpleague/omnipay-paypal/blob/master/src/RestGateway.php

Could definitely do it through something like phpdoc instead, although last I checked it used a conflicting version of phpparser. So maybe apigen or something?

**Comment by TysonAndre** [comment] 2018-01-18 19:15
Also, it seems like Psalm allows documenting properties of local variables (`@var Type $var->propName`). If so, that difference should also be documented. (e.g. from phpdoc2, or from the psr-5 draft at https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md )

`/** @var ClassMethod $this->function */` in src/Psalm/Checker/FunctionLikeChecker.php

**Comment by muglug** [comment] 2018-01-29 15:41
[DocumentationTest](https://github.com/vimeo/psalm/blob/d728bbb295c9c43b87072d749367b42aa513a38e/tests/DocumentationTest.php) now ensures that `issues.md` is complete and correct.

**Comment by muglug** [comment] 2018-01-30 05:22
> a list of phpdoc annotations Psalm supports
> a list of Psalm-specific docblock annotations

https://github.com/vimeo/psalm/blob/master/docs/supported_annotations.md

**Comment by nickyr** [comment] 2018-01-30 15:18
That's beautiful! Lot of features I didn't even know it had.

- What does RHS mean? An explanation/expansion would be helpful.
- When discussing `@psalm-*` annotations, refer the user to the Type Syntax section at the bottom so they know what the special types are.
- Incomplete sentence: `For example, we can suppress the possible`
- The example for @psalm-seal-properties doesn't make it clear what the -read or -write things mean. Also, not clear that -read and -write don't need to be specified.
- You say psalm uses @deprecated, but you don't say what it does with it.

**Comment by muglug** [comment] 2018-01-30 16:32
Thanks, I've made those changes

**Comment by TysonAndre** [comment] 2018-02-05 21:43
Another thing that needs to be done: Link to the docs folder from the wiki? (e.g. from the Wiki home page to docs/supported_annotations.md, etc, with appropriate descriptions)

The only reference I see to docs/ is in the wiki page Typing-in-Psalm.md

> `PHPDoc [allows you to specify](https://phpdoc.org/docs/latest/references/phpdoc/types.html#arrays) the  type of values the array holds with the annotation:`

**Comment by muglug** [comment] 2018-02-22 18:27
Fixed in latest

**Closed by muglug** 2018-02-22 18:27 UTC
