### ISSUE TITLE
totallyTyped is ignored if errorLevel is not in config

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#2832] opened 2020-02-18 06:47 UTC
I'm not sure if it's wanted behaviour, but it's quite confusing so I report it.

In config.xsd of psalm, errorLevel's default value is 1. However, when errorLevel is not present in psalm.xml, totallyTyped is ignored (it doesn't activate Mixed* if =true). When we manually add errorLevel=1, it now works.

It's quite confusing for existing Psalm.xml because it will disable Mixed* rules if config file is not changed while upgrading to 3.9

**Comment by muglug** [comment] 2020-02-18 13:54
Are you sure it's ignored? Current rules should set the level implicitly to 1 when `totallyTyped` is set to `true`: https://github.com/vimeo/psalm/blob/9866b292a40bc0258b1483428ea2f19baa7aed51/src/Psalm/Config.php#L828-L848

**Comment by simitter** [comment] 2020-02-18 14:30
I think problem may be that the totally_typed variable is a simplexml element and the comparision with === always results in the else branch to be used

**Comment by muglug** [comment] 2020-02-18 14:42
Thanks @simitter - fixed in 201d54f, I'll create a new release momentarily. I'll also investigate how Psalm allowed that bug.

**Closed by muglug** 2020-02-18 14:42 UTC

**Comment by muglug** [comment] 2020-02-18 14:50
https://github.com/vimeo/psalm/releases/tag/3.9.1

**Comment by muglug** [comment] 2020-02-18 17:55
This was caused by a bug which allowed objects with `__toString` to be compared to literal strings as part of an OR condition, now fixed.

```php
class A {
  public function __toString() {
    return "hello";
  }
}

function foo(A $a) : void {
  if ($a === "b" || $a === "c") {} // is now a bug
}
```
