### ISSUE TITLE
Psalm does not understand negation of comparison operators

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#7074] opened 2021-12-05 20:56 UTC
Psalm understands the following correctly:

```php
function test(int $a): void {
    if ($a >= 0) {
        sleep($a);
    }
}
```

But fails to understand the negation of this check:

```php
function test(int $a): void {
    if ($a < 0) {
        throw new Exception();
    }

    sleep($a);
}
```

> ERROR: ArgumentTypeCoercion - 8:11 - Argument 1 of sleep expects 0|positive-int, parent type int provided

https://psalm.dev/r/a1658f75f3

**Comment by orklah** [comment] 2021-12-05 21:03
duplicate of https://github.com/vimeo/psalm/issues/6797

short story: this is due to the limitations inherent on having a single type `positive-int`. This could be solved by integer ranges, but the implementation of integer ranges is hard to complete because of loop complexity

**Closed by orklah** 2021-12-05 21:03 UTC
