### ISSUE TITLE
Refinement of 0 | positive-int

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#5083] opened 2021-01-22 12:57 UTC
Psalm cannot refine `0 | positive-int` with `$number >= 0` condition. But with `$number > 0 || $number === 0` it can:

https://psalm.dev/r/0934227831

**Comment by orklah** [comment] 2021-01-22 14:06
duplicate of https://github.com/vimeo/psalm/issues/4996

**Closed** 2021-01-22 16:00 UTC
