### ISSUE TITLE
psalm should complain about string input if $allow_class = false in is_a function

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#4439] opened 2020-10-28 20:35 UTC
This is invalid
https://psalm.dev/r/61b64202dd
3rd argument needs to be true for this to work

**Comment by orklah** [comment] 2021-10-12 20:17
I'll close this as duplicate of https://github.com/vimeo/psalm/issues/4092 because I explained the solution there

**Closed by orklah** 2021-10-12 20:17 UTC
