### ISSUE TITLE
BC issue, help needed

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#7540] opened 2022-01-31 12:50 UTC
I updated psalm (dev-master) today and suddenly got lots of new errors, all pointing to same problem.

---

Consider stub file [like this one](https://github.com/psalm/psalm-plugin-symfony/blob/master/src/Stubs/common/Component/Form/AbstractType.stubphp): 

Before today, if users **did not** use template, psalm would not complain and assume ``T: mixed``. Which is totally fine, not all forms need correct type due to their dynamic nature. 

For example:

```php
class MyType extends AbstractType {}
```

would work **exactly** as if I have written:

```php
/** @extends AbstractType<mixed> */
class MyType extends AbstractType {}
```

With latest update, psalm requires this annotation and I can't find the issue that changed this behavior. The result is that all users of symfony/psalm and other stubs will suddenly get lots of errors.

---

Any suggestions how to mitigate the problem expect for ignoring ``MissingTemplateParam`` issue?

**Comment by weirdan** [comment] 2022-01-31 13:20
Refs #7492

**Comment by orklah** [comment] 2022-01-31 14:02
@zmitic thanks for the feedback!

We're in no particular rush for this one, Psalm 5 hasn't been released (even as alpha) yet, so there is still time to refine features. Glad we have people testing with master for that :)

The PR #7492 was made to be a feature ensuring people don't forget annotating their templates. It's supposed to mimick what PHPStan already does for quite some time (even on `array`).

You find the change too big? Do you have an idea of the number of errors in a typical symfony project?

@danog, do you have ideas about what we could do to reduce the impact on end projects?

**Comment by danog** [comment] 2022-01-31 14:36
@orklah I don't think there's any way to make this rule softer, apart from removing it altogether: this can indeed be considered a BC-breaking feature, and that's why it will be released in 5.0.

The raison d'être of this check is precisely to make sure eventual template types aren't forgotten about when extending a class, which is especially useful in the case of iterators.

It can also direct Psalm beginners in the right direction by introducing them to template types, directly indicating how they can help in iterators and other places.

**Comment by zmitic** [comment] 2022-01-31 14:39
>Glad we have people testing with master for that  :)


I am into extreme sports; skydiving, paintball, late Friday deploys and using unreleased products :smile: 



>Do you have an idea of the number of errors in a typical symfony project?

I don't have any errors, and my psalm setup is level 1. For example: when I noticed this change today, it took me < 30 mins to fix my forms, and make PR to remove some useless code in symfony plugin.


But I can't talk about other users.


>You find the change too big? 

Actually, I don't and I like this decision **a lot**. 

But these stubs I made have not been verified by core members; forms can be very dynamic in nature, especially with DataTransformers. 

So while I don't have a single issue, I am afraid lots of others might. It is not just for form stubs, but other stubbed packages as well.


---

Suggestion for Psalm5; 
treat ``MissingTemplateParam`` as ``info`` by default, even on level 1? That would give users time to upgrade their code.

**Comment by danog** [comment] 2022-01-31 15:27
>Suggestion for Psalm5;
 treat MissingTemplateParam as info by default, even on level 1? That would give users time to upgrade their code.

I'm happy that you agree with the design decision, but I really don't think this preventive measure is needed: users will gradually upgrade their code as they gradually upgrade to Psalm v5, that's the point of a major release: make breaking changes, and stop maintaining older versions so people will gradually adapt their codebases as they upgrade to the new major.

**Comment by zmitic** [comment] 2022-01-31 15:49
>However, I really don't think this preventive measure is needed: users will gradually upgrade their code as they gradually upgrade to Psalm v5, 

You are right, it does make more sense.

So different suggestion:

- how about ``MissingTemplateParam`` trigger ``info`` in 4.x branch by default, if that template comes from stub file?

**Comment by danog** [comment] 2022-01-31 15:59
> how about MissingTemplateParam trigger info in 4.x branch by default, if that template comes from stub file?

That sounds fun!
If @orklah/@weirdan are OK with it, I could send in a PR for that :D

**Comment by orklah** [comment] 2022-01-31 16:06
> > how about MissingTemplateParam trigger info in 4.x branch by default, if that template comes from stub file?
> 
> That sounds fun! If @orklah / @weirdan are OK with it, I could send in a PR for that :D

You want to check the user_defined property for that?

I'm afraid we just saw it was not reliable for now (we'll have to revert/disable your change on ReturnTypeWillChange because of that...)

**Comment by danog** [comment] 2022-01-31 16:11
>I'm afraid we just saw it was not reliable for now (we'll have to revert/disable your change on ReturnTypeWillChange because of that...)

I saw, I tried playing around a bit, replacing the `user_defined` check with

```php
        $storage->user_defined = true;
        if (class_exists($fq_classlike_name)) {
            $reflect = new ReflectionClass($fq_classlike_name);
            $storage->user_defined = !$reflect->isInternal();
        }
```

However I haven't yet figured out how to reproduce the original issue in the stub tests, will probably give it another go tomorrow.

**Comment by kissifrot** [comment] 2022-12-23 07:26
Just my 2 cents, migrating to psalm v5 added the `MissingTemplateParam` error for _all_ symfony form types we implemented :sweat_smile:

**Comment by danog** [comment] 2022-12-23 08:56
Yep, this is intended!

**Closed** 2022-12-23 10:32 UTC

**Comment by rogierknoester** [comment] 2023-01-12 10:20
Hi @danog, is this BC also intended for a case where a `parent::__construct` provides the type, like for Doctrine repositories?

https://psalm.dev/r/3672bc9542
