### ISSUE TITLE
Psalm chokes on array_s(p)lice() when arg one is an object property (but only sometimes)

### ISSUE THREAD

**Issue by Girgias** [vimeo/psalm#4828] opened 2020-12-11 03:26 UTC
This is a rather weird issue I'm hitting, and I'm also possibly miss-using the `@psalm-return` tag but I have reproducible with constants:

https://psalm.dev/r/b3a9df1717
https://psalm.dev/r/999e7fb021

The ``offset`` and ``length`` arguments should be correctly inferred to be int (and null for length) when the array to slice/splice comes from an object property.

If needed I can share the full class I'm working on in a gist.

**Comment by weirdan** [comment] 2021-07-18 20:31
Please share a minimal valid reproducer.

**Comment by orklah** [comment] 2021-08-10 17:59
Closing this as not reproduced. Array_slice and array_splice inference were much improved since this ticket creation, if there is still an issue, please open a new ticket

**Closed by orklah** 2021-08-10 17:59 UTC
Labels: more info needed
