### ISSUE TITLE
NonInvariantDocblockPropertyType with multiple inheritance

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#5387] opened 2021-03-14 21:53 UTC
I am not sure that this is a bug. But then I don't know how to annotate it properly.

https://psalm.dev/r/a475637df4

**Comment by weirdan** [comment] 2021-03-14 22:14
Duplicate of #5371, as far as I can tell.

**Closed by weirdan** 2021-03-14 22:14 UTC
