### ISSUE TITLE
Conditional interfaces

### ISSUE THREAD

**Issue by designermonkey** [vimeo/psalm#6175] opened 2021-07-25 14:06 UTC
Please see https://psalm.dev/r/105b581007

I'm sure I've done this before and it's worked in the PHP interpretor although I don't actually remember. I've tried this on PHP 7.4 and 8.

Is this error correct? Is this legal syntax?

**Comment by weirdan** [comment] 2021-07-25 14:56
It is valid syntax in PHP, but Psalm currently does not support conditional interfaces nor traits.

**Comment by designermonkey** [comment] 2021-07-25 16:07
Okidoke. Should I leave this open then as a reminder?

**Comment by weirdan** [comment] 2021-07-25 16:23
Yep, please do.

**Comment by weirdan** [comment] 2022-11-20 09:26
> Psalm currently does not support conditional interfaces nor traits.

Conditional traits are now supported.

**Comment by weirdan** [comment] 2022-11-24 07:47
Duplicate of #5338

**Closed by weirdan** 2022-11-24 07:48 UTC
Labels: enhancement
