### ISSUE TITLE
RedundantFunctionCall problem

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#8963] opened 2022-12-21 00:36 UTC
This is my  enum
https://psalm.dev/r/b147e05cf3

As you can see array_values is marked as RedundantFunctionCall but I'm using it to reset array indexes as the call to array_diff above produces an array with non continuous indexes. Is there a way to handle this case?

**Comment by jack-worman** [comment] 2022-12-21 03:10
The problem is that psalm does not like that array_column call because `value` is a property not a key: https://psalm.dev/r/ebd8c22399
You should use array_map instead: https://psalm.dev/r/cf56254b4e

**Comment by jack-worman** [comment] 2022-12-21 04:23
This works: https://psalm.dev/r/7faba56988
So Psalm just does not know about enums having properties. `\BackedEnum` should be thought of as `object{name: string, value: int|string}`

**Comment by weirdan** [comment] 2022-12-21 07:31
> Probably a bug in `ArrayColumnReturnTypeProvider`

Most likely.

**Comment by matiux** [comment] 2022-12-21 09:20
Thanks!
For now I try the solution of not using array_column, so doing:
```
$allLangValues = array_map(fn (Lang $lang): string => $lang->value, Lang::cases());
```

**Comment by danog** [comment] 2022-12-21 09:20
Actually, it's a bug in the get_object_vars return type provider, which is invoked by the array_column type provider: https://psalm.dev/r/22dca38fd8

**Comment by jack-worman** [comment] 2022-12-21 14:02
I am working on a fix for this.

**Comment by orklah** [comment] 2022-12-28 21:46
This was fixed :)

**Closed by orklah** 2022-12-28 21:46 UTC
Labels: bug, type providers, enum
