### ISSUE TITLE
!isset doesn't exclude null from type inference

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#5907] opened 2021-06-08 11:03 UTC
https://psalm.dev/r/bb3c83a40f

**Expected**: `$data: array{status: string}`, $data['status'] can't be null because !isset($data['status']) will lead to a RuntimeException.
is_null() condition is pointless here.
**Got**: `$data: array{status: null|string}`

**Comment by weirdan** [comment] 2021-06-08 11:07
Duplicate of #5828

**Closed by weirdan** 2021-06-08 11:07 UTC
