### ISSUE TITLE
[3.7.0] InvalidArgument - Calling empty on a boolean value is almost certainly unintended

### ISSUE THREAD

**Issue by Jeckerson** [vimeo/psalm#2390] opened 2019-11-28 23:17 UTC
Since version `3.7.0` appeared error, that in under question if it is really error.

Code:
```
if (!empty($arguments[$paramName]['have-option']) && $param == '') {
    throw new CommandsException("The parameter '$paramName' requires an option");
}
```

Error message:
> ERROR: InvalidArgument - src/Commands/Command.php:288:28 - Calling empty on a boolean value is almost certainly unintended

**Comment by muglug** [comment] 2019-12-01 15:25
Would you mind pasting the preceding code? Or try to reproduce it on psalm.dev?

**Comment by muglug** [comment] 2020-04-26 20:06
Closing because it's old

**Closed by muglug** 2020-04-26 20:06 UTC
