### ISSUE TITLE
Problem with "new static" in static method call

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#5747] opened 2021-05-11 10:52 UTC
I get the UnsafeGenericInstantiation error despite putting final in the constructor

https://psalm.dev/r/f9fe1e15bb

**Comment by weirdan** [comment] 2021-05-11 11:15
Constructor being final does not prevent a descendant to declare it has narrower type parameter with e.g. `@template-extends BasicServiceResponse<int>`

**Comment by matiux** [comment] 2021-05-11 12:19
Thank you @weirdan . So how can I fix?

**Comment by matiux** [comment] 2021-05-11 13:02
by the way, since the class is abstract, I can't do `new self`

**Comment by matiux** [comment] 2021-06-23 16:07
up
this is a shorter example

https://psalm.dev/r/ce85a892e2

**Comment by AndrolGenhald** [comment] 2021-12-13 22:59
@orklah Are you sure this is a bug? I think this is correct solution is to use `@psalm-consistent-templates` as noted in the documentation: https://psalm.dev/r/650ada1ab1

**Comment by orklah** [comment] 2021-12-13 23:12
Yep, I learned that tag existed not long ago. Closing this as not a bug indeed.

**Closed by orklah** 2021-12-13 23:12 UTC
Labels: bug, static
