### ISSUE TITLE
Psalm infers > 100% type coverage

### ISSUE THREAD

**Issue by DaveLiddament** [vimeo/psalm#6270] opened 2021-08-09 13:11 UTC
To recreate. Run Psalm on the the [SARB](https://github.com/DaveLiddament/sarb) codebase. It reports for me

```
Psalm was able to infer types for 100.0181% of the codebase
```

Running with `--stats` all files are 100% apart from [this one](https://github.com/DaveLiddament/sarb/blob/master/src/Domain/Utils/ArrayUtils.php), which is 103%.
```
103% src/Domain/Utils/ArrayUtils.php (-1 mixed)
```

I've created [a branch](https://github.com/DaveLiddament/sarb/tree/investigation/psalm-type-coverage-bug) with copies of `ArrayUtils.php` to help track down the issue further...

I made a copy of `ArrayUtils.php` called [`ArrayUtils2.php`](https://github.com/DaveLiddament/sarb/blob/investigation/psalm-type-coverage-bug/src/Domain/Utils/ArrayUtils2.php) and removed methods one at a time. Each time I'd run:

```
vendor/bin/psalm --stats --no-cache | grep ArrayUtils2
```

Trimming down `ArrayUtils2.php` to this: 

```
<?php

declare(strict_types=1);

namespace DaveLiddament\StaticAnalysisResultsBaseliner\Domain\Utils;

class ArrayUtils2
{
    /**
     * @param mixed $entity
     *
     * @throws ArrayParseException
     */
    public static function assertArray($entity): void
    {
        if (!is_array($entity)) {
            throw ArrayParseException::invalidType('base level', 'array');
        }
    }

}
```

I got 200% type coverage:

```
200% src/Domain/Utils/ArrayUtils2.php (-1 mixed)
```

I tried other combinations of the method (to see if the issue was with throwing an exception) and I am even more confused:

See [ArrayUtils3.php ](https://github.com/DaveLiddament/sarb/blob/investigation/psalm-type-coverage-bug/src/Domain/Utils/ArrayUtils3.php)

```
class ArrayUtils3
{
    /**
     * @param mixed $entity
     *
     * @throws Exception
     */
    public static function assertArray($entity): void
    {
        if (!is_array($entity)) {
            throw new Exception();
        }
    }
}
```

And [ArrayUtils4.php ](https://github.com/DaveLiddament/sarb/blob/investigation/psalm-type-coverage-bug/src/Domain/Utils/ArrayUtils4.php)

```
class ArrayUtils4
{
    /**
     * @param mixed $entity
     *
     * @throws Exception
     */
    public static function assertArray($entity): void
    {
        if (!is_array($entity)) {
            throw new Exception('A message');
        }
    }
}
```

Running `vendor/bin/psalm --no-cache --stats  | grep ArrayUtils` I get:

```
103% src/Domain/Utils/ArrayUtils.php (-1 mixed)
200% src/Domain/Utils/ArrayUtils2.php (-1 mixed)
0% src/Domain/Utils/ArrayUtils3.php (-1 mixed)
```

**NOTE** there is no record of `src/Domain/Utils/ArrayUtils4.php`

Let me know if there is any other info I can provide you with to help debug. 

---

Versions of Psalms I've tried this on (both give same result):
```
Psalm 4.6.1@e93e532e4eaad6d68c4d7b606853800eaceccc72
Psalm 4.7.2@83a0325c0a95c0ab531d6b90c877068b464377b5
```

```
PHP 8.0.3 (cli) (built: Mar  5 2021 08:36:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by DaveLiddament** [comment] 2021-08-09 13:22
@weirdan 

I still get the same issues on 4.9.2. 
```
vagrant@sarb:/vagrant$ vendor/bin/psalm -v
Psalm 4.9.2@00c062267d6e3229d91a1939992987e2d46f2393
```

```
vagrant@sarb:/vagrant$ vendor/bin/psalm --no-cache --stats | grep Arra
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 202 (29%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 202 (59%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 202 (89%)
░░░░░░░░░░░░░░░░░░░░░░
100% src/Domain/Utils/ArrayParseException.php (0 mixed)
103% src/Domain/Utils/ArrayUtils.php (-1 mixed)
200% src/Domain/Utils/ArrayUtils2.php (-1 mixed)
0% src/Domain/Utils/ArrayUtils3.php (-1 mixed)
```

My lunch break is over, but I'll try and recreate in a standalone project after work today.

**Comment by DaveLiddament** [comment] 2021-08-09 18:34
@weirdan I've recreated issue in a standalone project [here](https://github.com/DaveLiddament/psalm-bug-investigation)

Results from Psalm:

```
vendor/bin/psalm --stats --no-cache
Scanning files...
Analyzing files...

░░░░░░░░
------------------------------
No errors found!
------------------------------

Checks took 0.66 seconds and used 43.192MB of memory
Psalm was able to infer types for 114.2857% of the codebase
-----------------
100% src/ArrayParseException.php (0 mixed)
103% src/ArrayUtils.php (-1 mixed)
200% src/ArrayUtils2.php (-1 mixed)
0% src/ArrayUtils3.php (-1 mixed)
0% src/ArrayUtils5.php (-1 mixed)
```
Also there is no type coverage reported for:

-  `src/ArrayUtils4.php` (which is the same as `src/ArrayUtils3.php` but in src/ArrayUtils4.php a message is passed into the exception. 
- `src/ArrayUtils6.php` (which is the same as `src/ArrayUtils5.php` but in src/ArrayUtils6.php a message is passed into the exception. 

Seems to get different results depending on how and which exception is thrown if the `is_array` check returns false.

**Comment by orklah** [comment] 2021-08-10 18:10
Related to https://github.com/vimeo/psalm/issues/3660

**Comment by muglug** [comment] 2021-08-14 14:35
Dupe of #3660, closing (but thanks for the info, it led me to the culprit).

**Closed by muglug** 2021-08-14 14:35 UTC
