### ISSUE TITLE
ArrayObject with ARRAY_AS_PROPS flag

### ISSUE THREAD

**Issue by mathroc** [vimeo/psalm#6863] opened 2021-11-08 19:49 UTC
When an ArrayObject is constructed with the `ARRAY_AS_PROPS` flag, we should be allowed to access its properties the same way we're using array access on it

https://psalm.dev/r/eaa7947d82

**Comment by weirdan** [comment] 2021-11-08 19:52
@mathroc you need to click 'Get link' button before copying the url.

**Comment by mathroc** [comment] 2021-11-08 19:55
> @mathroc you need to click 'Get link' button before copying the url.

sorry about that, here is the correct link : https://psalm.dev/r/eaa7947d82 (I've updated the issue description too)

**Comment by orklah** [comment] 2021-11-08 20:09
I think we'll hit the same wall as in https://github.com/vimeo/psalm/issues/5035. Psalm is not currently able to store flags that makes the behaviour of an object change...

**Comment by mathroc** [comment] 2021-11-08 20:13
if that's not possible, how about allowing to declare properties with `@property` without having a `__get` magic method?

https://psalm.dev/r/d42513f53c

**Comment by orklah** [comment] 2021-11-08 20:25
This is a config to enable in your xml file: https://psalm.dev/r/b6dbbf7c78

**Comment by orklah** [comment] 2021-11-08 22:00
I'll consider this fixed. You seem to have found your answer, and aside from that, it's a duplicate of #5035 about flags in objects

**Closed by orklah** 2021-11-08 22:00 UTC
