### ISSUE TITLE
Intersection between UnitEnum / BackedEnum and Interface

### ISSUE THREAD

**Issue by hockdudu** [vimeo/psalm#10414] opened 2023-11-27 06:54 UTC
When a function has a parameter of `\BackedEnum&Interface` (intersection between Enum and Interface), Psalm throws an exception:

```
Psalm runner output: 

Internal Psalm error on line 47 - /vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php: Could not get class storage for backedenum
```

Here's the code: https://psalm.dev/r/4d1f328b6f

My use case is more or less the following: https://psalm.dev/r/7fb43699a6

In my case, I can fix it by just setting the parameter to `Interface` (remove the intersection with Enum), but still, here's the bug report. There could be valid cases where one needs to have an Enum (e.g. to get all cases) and still call the interface method at the same time.

(This can be reproduced with `\UnitEnum` as well)

**Comment by weirdan** [comment] 2024-02-10 03:57
Duplicate of #7520

**Closed by weirdan** 2024-02-10 03:57 UTC
Labels: bug, enum, intersections
