### ISSUE TITLE
Error on ignored Doctrine file

### ISSUE THREAD

**Issue by EtchAkhtar** [vimeo/psalm#4986] opened 2021-01-12 03:48 UTC
Please note psalm (4.3.2 and also tried dev-master) is erroring with following:

```
ERROR: InvalidDocblock - vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:74:5 - Badly-formatted @param in docblock for Doctrine\ORM\EntityRepository::__construct (see https://psalm.dev/008)
    /**
     * Initializes a new <tt>EntityRepository</tt>.
     *
     * @psalm-param Mapping\ClassMetadata<T>
     */
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $class)
```

psalm.xml is set to ignore vendor files, which it does other than the above:

```
    <projectFiles>
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
```

What is causing this to happen is a php class of mine built in Symfony5 that does:

```
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

class BaseRepository extends ServiceEntityRepository
{
    /**
     * @psalm-suppress InvalidDocblock
     */
    public function __construct(ManagerRegistry $registry, string $entityClass)
    {
        parent::__construct($registry, $entityClass);
    }
```

It is here the `parent::__construct($registry, $entityClass);` that makes psalm error on the Doctrine vendor class, as this is a superclass of mine.

If I comment this line out and don't call parent::_construct() then all is fine.

So psalm is following parent class constructors and reporting errors even if those files are in the ignored list.

What can I do?  This is failing CI

Mant thanks

**Comment by EtchAkhtar** [comment] 2021-01-12 03:51
> Hey @EtchAkhtar, can you reproduce the issue on https://psalm.dev ?

not sure how, it needs doctrine composer package to be installed to reproduce it

**Comment by weirdan** [comment] 2021-01-12 04:37
Duplicate of #4265

**Closed by weirdan** 2021-01-12 04:37 UTC
Labels: bug
