### ISSUE TITLE
UndefinedFunction, although file scanned

### ISSUE THREAD

**Issue by XedinUnknown** [vimeo/psalm#3758] opened 2020-07-06 10:08 UTC
Hi,

Working with WordPress here. When scanning plugin code, Psalm complains that function `__()` is not found. We have included the whole `vendor` directory in `<extraFiles>`, and can see `vendor/johnpbloch/wordpress-core/wp-includes/l10n.php` being analyzed when running `psalm --debug-by-line`: that is the file which contains `__()` function definition. And yet, we still get `UndefinedFunction` error:

```
ERROR: UndefinedFunction - src/Form/Configurator/FormControlElementsConfigurator.php:78:32 - Function Inpsyde\Idealo\WooCommerceSettings\Form\Configurator\__ does not exist (see https://psalm.dev/021)
                    'value' => __('Save', 'idealo-for-woocommerce-settings'),
```

It asks about `Inpsyde\Idealo\WooCommerceSettings\Form\Configurator\__` presumably because it "doesn't exist" in the global namespace.

Any ideas, please? Not sure how I'd be able to reproduce this on psalm.dev.

**Comment by weirdan** [comment] 2020-07-19 17:24
Is there a public repo where this can be reproduced?

**Comment by XedinUnknown** [comment] 2020-07-20 01:02
No, unfortunately.

**Comment by orklah** [comment] 2020-11-27 22:21
Did you try prefixing __ with \ to indicate global namespace explicitly?

**Comment by weirdan** [comment] 2020-11-27 22:30
Or adding a `use function __;`. This seems to help Psalm to properly understanding the function in a somewhat similar situation: https://psalm.dev/r/ac0393017e

**Comment by orklah** [comment] 2021-08-10 17:53
Closing this as duplicate of https://github.com/vimeo/psalm/issues/5791

**Closed by orklah** 2021-08-10 17:53 UTC
Labels: bug, more info needed
