### ISSUE TITLE
DateInterval::format() considered "possibly-mutating"

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#3358] opened 2020-05-14 07:33 UTC
```php
<?php declare(strict_types=1);
/**
 * @psalm-immutable
 */
final class C
{
	private DateTimeImmutable $a;
    
    private DateTimeImmutable $b;
    
    public function __construct(DateTimeImmutable $a, DateTimeImmutable $b)
    {
        $this->a = $a;
        $this->b = $b;
    }
    
    public function numberOfDays(): int
    {
        return (int) $this->b->diff($this->a)->format('%a') + 1;
    }
}
```
https://psalm.dev/r/332288b1ea
```
Psalm output (using commit 48504aa): 

ERROR: ImpureMethodCall - 19:48 - Cannot call an possibly-mutating method DateInterval::format from a mutation-free context
```
* `$this->a` is immutable
* `$this->b` is immutable
* `$this->b->diff($this->a)` returns a `DateInterval` instance
* The creation of a `DateInterval` instance does not have a side effect
* `DateInterval::format()` generates a string representation of a `DateInterval` instance

**Comment by gharlan** [comment] 2020-12-16 23:11
some more methods/functions: https://psalm.dev/r/373cc81b14
I think they should be all marked as mutation-free.

**Comment by gharlan** [comment] 2020-12-17 14:59
Hmm, I think my code above is not correct. The function should be mutation-free instead of pure:
https://psalm.dev/r/0d9ac83849

But the issue is the same, these methods/functions should be mutation-free.
I would like to help. But where is the correct place to mark core functions/methods as mutation-free?

**Comment by weirdan** [comment] 2023-08-26 20:14
Seems to be fixed.

**Comment by weirdan** [comment] 2023-08-26 20:14
https://psalm.dev/r/332288b1ea

**Closed by weirdan** 2023-08-26 20:14 UTC
Labels: bug, easy problems, internal stubs/callmap, Help wanted
