### ISSUE TITLE
Generic type inference regression bug

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#6611] opened 2021-10-08 14:51 UTC
I started experiencing this issue after updating Psalm. I was several releases behind before I updated to 4.10.0. Here is my attempt at a simplish reproduce that hopefully is the same issue.

https://psalm.dev/r/e0a37d1235

**Comment by orklah** [comment] 2021-10-09 12:58
A little context as to why Psalm is emitting an issue here.

It is trying to check that the three T you're declaring are coherent, so it starts to resolve them:
- new A() is `A<T of mixed>`
- [] is `array<empty, empty>`
- fn(int $num) ... is a `Closure(int)`

So now it's trying to check the consistency between the three and it gets `mixed, empty, int`. One is the top type, one is the bottom type and the third is int.
So it's telling you to be have the same types everywhere.

That's why you get a `mixed` should be an `int`. This is resolvable if you add upper bounds to your templates : https://psalm.dev/r/b2349c1e09

The second one is more tricky because empty is a weird special type so the interactions when you try to use it as a template are weird. I think we can exclude it from this check if necessary.

Are you okay with the changes I made in the example above? If so, we'll consider excluding empty so that you example pass.

**Comment by still-dreaming-1** [comment] 2021-10-12 13:13
Most of those examples require you to lock down the template type within the template itself, which is not always desirable. The middle one only provides a way to override the type in a way that disables some of the type checking. For example, this shows no issues, even though a `new A()` is definitely not a `new B()`.

https://psalm.dev/r/640f3af7d1

**Comment by still-dreaming-1** [comment] 2021-10-12 13:22
It's okay. I think we have merely shown that my reproduce code doesn't illustrate the issue I'm trying to report very. I will try to come up with a really good example, which may take some time. Thanks for trying to help.

**Comment by still-dreaming-1** [comment] 2021-10-15 13:15
I guess when you are working entirely with code you wrote, the empty array thing is not that big of a deal. I don't normally pass empty arrays around intentionally except in messy code that can be cleaned up. Let's say some code is returning a list or an array. It would be better if the method were typed to return a `non-empty-list` or `non-empty-array`. If it needs to be able to return an empty array, the return type should be a union type with null where null gets returned instead of an empty array. This way an empty array is never returned. It is easier to check for null than empty and the rest of the types are more likely to be typed correctly for Psalm to notice that you didn't check for null, more likely than for it to notice you didn't check for empty.

However, there are still going to be situations where an empty array must be passed. One might be working with someone else's library or built in function that takes an array, and for some reason they need to pass an empty array. If that function were typed such that it takes a specific type of array, and it complained that empty was not allowed, well that doesn't sound right to me. I don't think the programmer should have to change one of their templates to covariant or override the type of the array. The first example in my previous comment is what I think should be valid somehow.

**Comment by orklah** [comment] 2021-10-16 20:53
It's okay, it can wait until you're more familiar :)

From what I can see, it's a minor change but take your time!

Don't hesitate to ping me if you need help

**Comment by orklah** [comment] 2021-11-28 09:07
I made the fix that I suggested, but when trying to find the example this was supposed to fix, I couldn't find a good reproducer.

The first example is not solved by excluding empty, it would be solved by removing the mixed case. The mixed case comes from `new A()` who is an `T of mixed` that will be pushed to a `fn (int $num)` so it definitely doesn't make sense.

Whenever I try to remove the mixed case to only stay with the int case and empty case, the issue disappear or an unrelated one appears.

I think our whole discussion here was based on something that doesn't happen (empty being forbidden in combination with another template type) and on confusion about covariance in template.

I'll close this because the whole issue is just confusing to me now, but feel free to reopen with a reproducer more aligned with your real issue so we can have a real case to discuss about

**Closed by orklah** 2021-11-28 09:07 UTC
Labels: easy problems, templates, Help wanted
