### ISSUE TITLE
Unable to determine the type => is_string($s = $arr[0])

### ISSUE THREAD

**Issue by mj4444ru** [vimeo/psalm#8040] opened 2022-06-01 17:15 UTC
At first glance, everything should be obvious.

https://psalm.dev/r/6d2c7e5142

**Comment by weirdan** [comment] 2022-06-01 17:19
Mind elaborating why you think there's a problem here? I see `$s` is assigned `mixed` and Psalm tells you that.

**Comment by AndrolGenhald** [comment] 2022-06-01 17:39
I think we'll treat this as a duplicate of #8035. Either it'll be fixed there when/if the other issue is fixed, or we'll decide we'd rather keep this behavior and it won't be fixed.

Actually though, the behavior _is_ technically different, it's just functionally identical _in this case_, but if the function were to be changed it could be potentially dangerous: https://psalm.dev/r/571e2823f9. I think @orklah's suggestion [here](https://github.com/vimeo/psalm/issues/8035#issuecomment-1142363380) is probably a good one though, since we can suppress the `MixedAssignment` but still treat the variable as `mixed` to show issues later on.

**Closed by AndrolGenhald** 2022-06-01 17:39 UTC
