### ISSUE TITLE
Array by reference incorrectly hinted by auto fixer

### ISSUE THREAD

**Issue by AJenbo** [vimeo/psalm#2878] opened 2020-02-25 16:18 UTC
This issue produces invalid PHP when calling `psalm --alter --issues=MissingParamType`

input
```
/**
 * @param array $var
 */
function callMe(&$var): void
{}
```
result:
```
/**
 * @param array $var
 */
function callMe(&array $var): void
{}
```
expceted:
```
/**
 * @param array $var
 */
function callMe(array &$var): void
{}
```

**Comment by AJenbo** [comment] 2020-02-25 16:20
@psalm-github-bot I don't belive that allows me to run the fixers.

**Comment by muglug** [comment] 2020-02-25 18:24
Dupe of #2857, fixed in master (but not yet released)

**Closed by muglug** 2020-02-25 18:24 UTC
