### ISSUE TITLE
Fatal error if comment has asterisk

### ISSUE THREAD

**Issue by bgpastukh** [vimeo/psalm#1844] opened 2019-06-24 14:40 UTC
Hello, required swagger-php and now psalm fails because of this line https://github.com/zircote/swagger-php/blob/2.x/src/Annotations/Swagger.php#L184
Who should fix this problem? Or can i skip this file during analyze?

**Comment by muglug** [comment] 2019-06-24 22:13
Sorry - I'll just fix and release tonight

**Comment by muglug** [comment] 2019-06-25 21:58
Actually this is a dupe of https://github.com/vimeo/psalm/issues/1730, and should be fixed in the two most recent releases

**Closed by muglug** 2019-06-25 21:58 UTC
