### ISSUE TITLE
Some generics lead to unexpected issues when it comes to instantiation

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#8430] opened 2022-08-23 09:09 UTC
Hey guys,

I have no idea how to properly explain my problem, therefore, I've just added a codesample.

https://psalm.dev/r/c08beb61c6

So whenever I have something like this, I would expect psalm not telling me that this does not align with the annotation.
If I instantiate an empty queue, etc. - I'd expect it to be fulfilled since there is no special detail added.

Until nothing is added to the queue, everything should be fine.
If something is added to the queue via the property, it should align with the annotation.
If something is added to the queue within the `__construct`, psalm might be able to understand what was added and should - ofc - tell me the issue.

As of now, psalm treats the empty queue as invalid while I would expect it to be okay until an unsupported value is added.
Can you follow my reasoning?

**Comment by AndrolGenhald** [comment] 2022-08-23 14:32
It's possible in some future version someone might implement better type inference (like hindley-milner), but right now a template's type is set when cloned/constructed and future code can't change that type (barring annotations forcibly overriding it). Closing as a duplicate of #8066.

**Closed by AndrolGenhald** 2022-08-23 14:32 UTC
