### ISSUE TITLE
FEAT: Implement a pretty print error messages option for CLI output 

### ISSUE THREAD

**Issue by Adamoc14** [vimeo/psalm#10101] opened 2023-08-11 14:42 UTC
I was working on a project using complex types for psalm. 

When debugging the psalm errors, I find it very hard to isolate the error as the received types and the expected types are all squished together. 

I was wondering is there any way you could include a `--pretty-print` flag or another cli option that would make this a much easier process.

This option would essentially just format the output a little clearer, providing a more improved and easier to reason about representation of the types. 

Consequently, this would make it more efficient to identify the actual error at hand. 

Here's the sort of error I would like formatted a lot cleaner and easier to read.

The error: 
```sh
ERROR: InvalidArgument - ?.php:193:67 - Argument 5 of ?\SearchQuery::withDefaults expects array{categories?: 
list<int|null|string>, destinations?: list<int|null|string>, from?: null|string, groupType?: null|string, mostLikely?: array{exclude: bool, 
most: string}, pax?: int|null, products?: list<int|null|string>, time?: null|string, to?: null|string}|null, but array{categories?: 
list<int|string>|null, destinations?: list<int|string>|null, from?: string, groupType?: "Private"|"SmallGroup", mostLikely: array<empty, 
empty>, pax?: int, products?: list<int|string>|null, sr?: string, time?: string, to?: string} provided (see https://psalm.dev/004)
    return self::withDefaults($sortBy, $sortOrder, $skip, $limit, $filters);
```

Proposed Format (Diff format?): 

```diff
ERROR: InvalidArgument - ?.php:193:67 - Argument 5 ($filters|{ARGUMENT_NAME}) of  ?\SearchQuery::withDefaults 
- expected
+ received
array {
-    categories?: list<int|null|string>, 
+    categories?: list<int|string>|null, 
-    destinations?: list<int|null|string>, 
+    destinations?: list<int|string>|null, 
-    from?: null|string, 
+    from?: string, 
-    groupType?: null|string, 
+    groupType?: string, 
-    mostLikely?: array{exclude: bool, most: string}, 
+    mostLikely: array<empty, empty>, 
-    pax?: int|null, 
+    pax?: int, 
-    products?: list<int|null|string>, 
+    products?: list<int|string>|null, 
+    sr?: string, 
-    time?: null|string, 
+    time?: string, 
-    to?: null|string
+    to?: string
} | null
(see https://psalm.dev/004)
return self::withDefaults($sortBy, $sortOrder, $skip, $limit, $filters);
```

**Comment by weirdan** [comment] 2023-08-13 00:19
Duplicate of #3379.

Feel free to comment on that issue instead.

**Closed** 2023-08-13 00:19 UTC
