### ISSUE TITLE
Class constants where value starts with an operand are not recognized

### ISSUE THREAD

**Issue by bitwise-operators** [vimeo/psalm#8307] opened 2022-07-22 06:54 UTC
If the value for a class constant starts with an operand, like `!` or `~`, Psalm doesn't register it, and throws an `UndefinedConstant` error.

https://psalm.dev/r/b100090d84

**Comment by bitwise-operators** [comment] 2022-07-22 08:21
As an aside, I've had a quick look through the code to see if I could fix this, but I'm having a hard time figuring out what part of the code this is likely to be in. If someone could give a pointer where this is likely to originate, I'd be happy to give it another go.

**Comment by AndrolGenhald** [comment] 2022-07-22 15:13
My first guess would be it's a parsing issue in either `ParseTreeCreator` or `TypeParser`, but it's possible the issue is somewhere else as well.

**Comment by weirdan** [comment] 2022-11-10 05:18
Fixed in #8360

**Closed by weirdan** 2022-11-10 05:18 UTC
Labels: bug, class const
