### ISSUE TITLE
Asserting array types 

### ISSUE THREAD

**Issue by vasily-kartashov** [vimeo/psalm#1091] opened 2018-11-21 23:31 UTC
Can we add the ability to recognise assertions that apply to all array elements?

To illustrate the point, this works as expected:

```
/**
 * @param string|int $a
 * @return int
 */
function assert_element($a) : int {
    assert(!is_string($a));
    return $a;
}
```

But these two fail:

```
/**
 * @param array<string|int> $a
 * @return array<int>
 */
function assert_value($a) {
    foreach ($a as $v) {
        assert(!is_string($v));
    }
    return $a;
}

/**
 * @param array<mixed,mixed> $a
 * @return array<int,mixed>
 */
function assert_key($a) {
    foreach ($a as $k => $_) {
        assert(is_int($k));
    }
    return $a;
}
```

https://getpsalm.org/r/d1471d1548

**Comment by muglug** [comment] 2018-11-21 23:47
Dupe of https://github.com/vimeo/psalm/issues/649

**Closed by muglug** 2018-11-21 23:47 UTC

**Comment by muglug** [comment] 2018-11-21 23:49
And, like, really really hard. If you can think of a way to do this I'm all ears.

**Comment by muglug** [comment] 2018-11-22 00:09
In the meantime, you can rewrite like https://getpsalm.org/r/5e058936d3

**Comment by vasily-kartashov** [comment] 2018-11-22 00:15
That's cool, thank you!
