### ISSUE TITLE
Error on instance that can't reach block of code.

### ISSUE THREAD

**Issue by mcneely** [vimeo/psalm#2814] opened 2020-02-14 00:18 UTC
Consider the following snippet: https://psalm.dev/r/e39363546e

I keep getting :

> ERROR: TooManyArguments - src/Processor.php:109:32 - Too many arguments for method McNeely\ETL\Interfaces\ExtractorInterface::run - expecting 0 but saw 1
>             $output = $action->run($supported);

Even though ExtractorInterface can never reach that line.

**Comment by muglug** [comment] 2020-02-14 17:25
Can you reproduce with an example that shows the error you're getting?

**Comment by mcneely** [comment] 2020-02-17 14:50
I'm not following you. The code snippet generates that error. (Line 9) But there's no way that that interface can hit that.

**Comment by weirdan** [comment] 2020-02-17 14:52
@mcneely psalm.dev actually (correctly) reports the error on line 4, where you reference `$action` for the first time.

**Comment by mcneely** [comment] 2020-02-17 22:52
@weirdan Ignore the output.  I used the link just for the snippet. If you looked at the error in my original message above you'll see that psalm is throwing a false error for ExtractorInterface (line 9) but there's no way ExtractorInterface can reach line 9 because the if checks are limiting it to Transformer and Loader Interfaces. None of which have ExtractorInterface as a parent.

**Comment by weirdan** [comment] 2020-02-17 23:53
Your snippet is incomplete, so it's hard to say what `$action` type is. Does it look similar to this: https://psalm.dev/r/91fb7d277e ?

**Comment by mcneely** [comment] 2020-02-18 00:02
@weirdan yes, I hadn't realized that got saved.  They all extend off an empty BaseInterface class. The actual function has BaseInterface as $action's type.

**Comment by muglug** [comment] 2020-02-18 00:10
oh then I think this is a dupe of https://github.com/vimeo/psalm/issues/1843?

**Comment by mcneely** [comment] 2020-02-18 00:31
Possibly, the difference there's no function in the parent, just in the children.

**Comment by muglug** [comment] 2020-02-18 00:55
yeah, going to close this then – for now just ignore the error.

**Closed by muglug** 2020-02-18 00:55 UTC
Labels: more info needed
