### ISSUE TITLE
Badly placed parenthesis in conditional return causes crash

### ISSUE THREAD

**Issue by gsteel** [vimeo/psalm#8251] opened 2022-07-13 10:25 UTC
I hope this issue isn't just noise 🤞

In short, if you mess up where you close parenthesis for a conditional return, psalm crashes rather than yield an `InvalidDockblock` issue:

https://psalm.dev/r/cea33e07ae

**Comment by AndrolGenhald** [comment] 2022-07-13 16:01
Turns out I ran into this myself! Duplicate of #7575, I'll try to look at that in the next week.

**Closed by AndrolGenhald** 2022-07-13 16:01 UTC
Labels: bug, causes crash
