### ISSUE TITLE
docblock defined type cannot be used in @extends

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#4607] opened 2020-11-18 16:29 UTC
Two use cases of extends: https://psalm.dev/r/8d207f9f2c

First works as expected.
But second is wrong.

**Comment by klimick** [comment] 2020-11-20 09:25
Probably it is related: https://psalm.dev/r/449a712f9c

**Comment by weirdan** [comment] 2020-11-25 03:53
Duplicate of #4240

**Closed** 2020-11-25 03:53 UTC
