### ISSUE TITLE
Junit report can't be parsed by gitlab CI

### ISSUE THREAD

**Issue by djeux** [vimeo/psalm#2748] opened 2020-02-05 08:17 UTC
When the junit report is generated, it contains an xml that is not compatible with gitlabs. 
Looking closer at the generated file, it has multiple `<testsuite>` elements nested inside each other. 

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite>
        <testsuite>
          .....
        </testsuite>
        <testsuite>
          .....
        </testsuite>
    </testsuite>
</testsuites>
```
instead of the correct one (which is generated by other tools, for example Codesniffer, phpunit)
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite>
        ...
    </testsuite>
    <testsuite>
        ...
    </testsuite>
</testsuites>
```

**Comment by muglug** [comment] 2020-02-05 13:50
The source is here: https://github.com/vimeo/psalm/blob/master/src/Psalm/Report/JunitReport.php

Would you be able to create a PR to match the expected shape?

cc @m50

**Comment by djeux** [comment] 2020-02-05 13:54
Will do

**Comment by m50** [comment] 2020-02-05 14:23
I don't currently use the junit reports generated from psalm, but from my converter that psalm utilized, and those work correctly in my gitlab instance.

Also for reference, multiple nestes test suites is how the phpunit junit report is generated.

I'll test the psalm junit reports in my gitlab, and see if I can figure out what the issue is as well.

**Comment by djeux** [comment] 2020-02-05 14:49
@m50 true, just checked phpunit, format is the same. Just for some reason gitlab doesn't like the Junit produced by psalm.
What is the converter you use?

**Comment by m50** [comment] 2020-02-05 15:01
@djeux The converter is one I made: https://github.com/m50/psalm-json-to-junit

It takes in the json reports and outputs junit reports. Those reports get read from our Gitlab just fine (In fact, when I was writing it, I was testing it against gitlab).

Psalm's implementation was based on mine (which is why I was cc'd in), so it's weird if there is a discrepancy.

**Comment by muglug** [comment] 2020-02-05 15:20
@m50 mind using the Psalm one and seeing if output it at all different? You could presumably check offline.

**Comment by djeux** [comment] 2020-02-05 15:36
Already did that, the main different I see is in the count of "tests" in the parent testsuite 'tests' attribute.

Psalm one:
```
  <testsuite failures="8" warnings="11298" name="psalm" tests="11306" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/junit-team/junit5/r5.5.1/platform-tests/src/test/resources/jenkins-junit.xsd">
```
Converter one:
```
  <testsuite failures="8" warnings="11298" name="psalm" tests="1296" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/junit-team/junit5/r5.5.1/platform-tests/src/test/resources/jenkins-junit.xsd">
```

Also, the converted file did work in gitlab CI. So there is a difference apparently

**Comment by m50** [comment] 2020-02-05 15:41
They are actually very different, from what I am seeing:

From conversion:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite failures="1" warnings="0" name="psalm" tests="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/junit-team/junit5/r5.5.1/platform-tests/src/test/resources/jenkins-junit.xsd">
    <testsuite name="src/Model.php" file="src/Model.php" assertions="1" failures="1" warnings="0" tests="1">
      <testcase name="src/Model.php:35" file="src/Model.php" class="InvalidScalarArgument" classname="InvalidScalarArgument" line="35" assertions="1">
        <failure type="InvalidScalarArgument">message: Argument 2 of method_exists expects string, int provided
type: InvalidScalarArgument
snippet: if (method_exists($this, $setter)) {
selected_text: $setter
line: 35
column_from: 38
column_to: 45
</failure>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
```

If you use `psalm --output-format=junit --report=test.xml` It outputs the xml format:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<report>
  <item>
    <severity>error</severity>
    <line_from>35</line_from>
    <line_to>35</line_to>
    <type>InvalidScalarArgument</type>
    <message>Argument 2 of method_exists expects string, int provided</message>
    <file_name>src/Model.php</file_name>
    <file_path>/Users/marisa/devfiles/mine/spamtitan-api/src/Model.php</file_path>
    <snippet>            if (method_exists($this, $setter)) {</snippet>
    <selected_text>$setter</selected_text>
    <from>792</from>
    <to>799</to>
    <snippet_from>755</snippet_from>
    <snippet_to>803</snippet_to>
    <column_from>38</column_from>
    <column_to>45</column_to>
  </item>
</report>
```

But the output into the console is as:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite failures="1" warnings="0" name="psalm" tests="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/junit-team/junit5/r5.5.1/platform-tests/src/test/resources/jenkins-junit.xsd">
    <testsuite name="src/Model.php" file="src/Model.php" assertions="1" failures="1" warnings="0" tests="1">
      <testcase name="src/Model.php:35" file="src/Model.php" class="InvalidScalarArgument" classname="InvalidScalarArgument" line="35" assertions="1">
        <failure type="InvalidScalarArgument">message: Argument 2 of method_exists expects string, int provided
type: InvalidScalarArgument
snippet: if (method_exists($this, $setter)) {
selected_text: $setter
line: 35
column_from: 38
column_to: 45
</failure>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
```

Which as far as I can see, is exactly the same as the converted one.

**Comment by m50** [comment] 2020-02-05 15:42
It appears that when you set the output format to junit, but then assign a report file, it uses the XML formatter, not the junit one.

**Comment by djeux** [comment] 2020-02-05 15:45
The command I used was (that gitlab was unable to parse)
```
vendor/bin/psalm --report=junit.xml --report-show-info=false --show-info=false
```

**Comment by m50** [comment] 2020-02-05 15:53
Oh interesting, the name has to be exactly junit.xml to get the junit report. Alrighty. Checking that.

**Comment by djeux** [comment] 2020-02-05 15:54
Not exactly, but has to contain `junit.xml` in it. For example `psalm.junit.xml` also generates the junit format

**Comment by m50** [comment] 2020-02-05 16:05
Ahh, good to know. We haven't been using the junit output from psalm, we've been using the converter.

So I tested with our gitlab that very simple issue (on a relatively tiny codebase), and it works without a problem, so it might be due to something in your code base.

The only difference I see in what you've shared is the number of tests. I get the number of tests from how many entries are in the JSON, however I assume psalm is getting it from a file count? Is that how many php files are being tested (11306)? 

Maybe it's down to that?

**Comment by djeux** [comment] 2020-02-05 16:48
In the progress bar, the number of tested files is about 1800.
I will try to convert the file and play with the original to figure out what exactly in the original junit.xml can cause it

**Comment by m50** [comment] 2020-02-05 17:05
Can you by chance get a diff of the junit.xml and the converted one?

This would help with seeing what all the differences are.

**Comment by dq5studios** [comment] 2020-03-08 04:09
I validated it against the xsd and fixed a couple other errors in the output.
Gitlab parses this version just fine.

**Comment by muglug** [comment] 2020-04-26 23:53
Closing, feel free to reopen if anyone has more issues

**Closed by muglug** 2020-04-26 23:53 UTC
Labels: more info needed
