### ISSUE TITLE
Weird behavior with references and anonymous functions

### ISSUE THREAD

**Issue by neclimdul** [vimeo/psalm#7777] opened 2022-03-12 22:04 UTC
When you pass a reference in a use to allow a function to modify a variable it seems psalm looses tract of the typing.

https://psalm.dev/r/9bf9e1f3c6

Looking at the hints in the snippets it seems to think its null inside the function? And then after the call it treats it as mixed. The internal code can provably only modify the value to a string though so it shouldn't fail.

Admittedly this has a ton of code smell and is a pretty terrible design but you don't always get to choose the design of the library you're stuck with. :-D

I also wasn't sure how to search for this problem but I did try. Hopefully didn't miss another report that actually captures this problem better already.

**Comment by AndrolGenhald** [comment] 2022-03-12 22:48
Duplicate of #7568, this might eventually improve by my suggestion [here](https://github.com/vimeo/psalm/issues/7568#issuecomment-1029079772) but as far as I know there are no immediate plans to work on that.

**Closed by AndrolGenhald** 2022-03-12 22:48 UTC

**Comment by neclimdul** [comment] 2022-03-13 01:06
I'm sorry that's closed... How is this going to get fixed if all the issues are closed?

**Comment by orklah** [comment] 2022-03-13 07:33
@neclimdul Thanks for your concern but with 800+ issues open and raising rapidly, we would be happy to even be able to process each critical issue. Given this is not a priority and judging on the number of times it was suggested, I don't worry we'll have dozens more by the time we can actually look at it.

But if you want to help us getting there quicker, feel free to pick one of the "good first issue" here: https://github.com/vimeo/psalm/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by neclimdul** [comment] 2022-03-14 14:41
I appreciate that. Like truely to my core. I help maintain a project that currently has over 20k issues so I both understand the need to close issue but also don't have time to help unless its getting something in my way fixed and need a way to track that this feature is broken. So could there be some documentation or general open issue to document this that I can at least reference?
