### ISSUE TITLE
Default baseline file?

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#6356] opened 2021-08-23 09:35 UTC
Hi,

From https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#using-a-baseline-file

I found running `psalm --set-baseline` does nothing, where i expected it would took the baseline file as configured in psalm.xml (errorBaseline) :thinking: since providing the same value (as documented) does work. However i thought the docs did to initally generate it also :)

Also i believe the term "update" is rather implicit: "to remove references to things that have been fixed", if not confusing vs. "set".

WDYT?

**Comment by orklah** [comment] 2021-08-28 16:51
Not sure I followed you.

--set-baseline expect a filename, it will add the filename to your current xml config and rewrite the complete baseline in it
--update-baseline does not expect an argument and it will only remove outdated issues (it will not add new ones)

If the suggestion is to be able to remove the filename for --set-baseline, then it's a duplicate of https://github.com/vimeo/psalm/issues/5831. If there is another thing, can you explain it further?

**Comment by ro0NL** [comment] 2021-08-28 16:59
Ack. I have the same POV as https://github.com/vimeo/psalm/issues/5831#issuecomment-857521086 :+1: 

I do believe _update_ can be interpreted as both "add" and "remove".

IIUC we could add a third option, eg.`--sync-baseline [optional-filename]` that invokes both steps.

My usecase is dusting the develop branch :) eg. updating basefile with the current branch's status quo.

**Comment by orklah** [comment] 2021-08-28 18:43
Feel free to propose a PR to make the filename optional, I think this would be accepted. I'll close this as duplicate of #5831 then

**Closed by orklah** 2021-08-28 18:43 UTC
